CREATE TABLE sales_calculator_saved (
 id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES identity_users(id),
 kind TEXT NOT NULL CHECK(kind IN ('template','workspace')),
 name TEXT NOT NULL, revision INTEGER NOT NULL CHECK(revision > 0),
 payload TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL,
 _order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE
);
CREATE INDEX sales_calculator_saved_owner ON sales_calculator_saved(owner_id,updated_at);
UPDATE schema_metadata SET value='2' WHERE key='workbench_sales_schema_version';
