ALTER TABLE identity_users ADD COLUMN ai_enabled integer NOT NULL DEFAULT 0 CHECK (ai_enabled IN (0,1));

ALTER TABLE projects ADD COLUMN owner_id text REFERENCES identity_users(id),
    ADD COLUMN revision integer NOT NULL DEFAULT 1 CHECK (revision > 0),
    ADD UNIQUE (id,owner_id);
ALTER TABLE conversations ADD COLUMN owner_id text REFERENCES identity_users(id),
    ADD COLUMN revision integer NOT NULL DEFAULT 1 CHECK (revision > 0),
    ADD UNIQUE (id,owner_id),
    ADD FOREIGN KEY (project_id,owner_id) REFERENCES projects(id,owner_id);
ALTER TABLE conversation_messages ADD COLUMN owner_id text REFERENCES identity_users(id),
    ADD COLUMN role text NOT NULL DEFAULT 'user' CHECK (role IN ('user','assistant','tool')),
    ADD COLUMN task_id text,
    ADD COLUMN submission_request jsonb,
    ADD COLUMN submission_receipt jsonb,
    ADD UNIQUE (id,owner_id,conversation_id),
    ADD UNIQUE (id,owner_id,task_id),
    ADD FOREIGN KEY (conversation_id,owner_id) REFERENCES conversations(id,owner_id);
ALTER TABLE tasks DROP CONSTRAINT tasks_status_check;
ALTER TABLE tasks ADD COLUMN owner_id text REFERENCES identity_users(id),
    ADD COLUMN revision integer NOT NULL DEFAULT 1 CHECK (revision > 0),
    ADD CONSTRAINT tasks_status_check CHECK (status IN ('created','running','waiting','completed','stopped','failed','blocked')),
    ADD UNIQUE (id,owner_id,conversation_id),
    ADD UNIQUE (id,owner_id),
    ADD FOREIGN KEY (conversation_id,owner_id) REFERENCES conversations(id,owner_id),
    ADD FOREIGN KEY (project_id,owner_id) REFERENCES projects(id,owner_id),
    ADD FOREIGN KEY (message_id,owner_id,conversation_id) REFERENCES conversation_messages(id,owner_id,conversation_id);
UPDATE conversation_messages m SET task_id=t.id FROM tasks t WHERE t.message_id=m.id;
ALTER TABLE conversation_messages ADD CONSTRAINT message_task_source
    FOREIGN KEY (task_id,owner_id,conversation_id) REFERENCES tasks(id,owner_id,conversation_id) DEFERRABLE INITIALLY DEFERRED;
DROP INDEX conversation_messages_submission_key;
CREATE UNIQUE INDEX conversation_messages_submission_key ON conversation_messages(owner_id,submission_key) WHERE submission_key IS NOT NULL AND owner_id IS NOT NULL;

CREATE TABLE task_runs (
    id text PRIMARY KEY,
    task_id text NOT NULL,
    owner_id text NOT NULL REFERENCES identity_users(id),
    input_message_id text NOT NULL,
    status text NOT NULL CHECK (status IN ('running','waiting','completed','stopped','failed','blocked')),
    started_at text NOT NULL,
    ended_at text,
    waiting_reason text,
    stop_reason text,
    runtime_version text NOT NULL CHECK (length(trim(runtime_version)) > 0),
    _order bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    FOREIGN KEY (task_id,owner_id) REFERENCES tasks(id,owner_id),
    FOREIGN KEY (input_message_id,owner_id,task_id) REFERENCES conversation_messages(id,owner_id,task_id),
    CHECK ((status IN ('running','waiting')) = (ended_at IS NULL))
);
CREATE UNIQUE INDEX task_runs_active ON task_runs(task_id) WHERE status IN ('running','waiting');
CREATE INDEX task_runs_history ON task_runs(task_id,_order);
CREATE INDEX projects_owner ON projects(owner_id,_order);
CREATE INDEX conversations_owner ON conversations(owner_id,_order);
CREATE INDEX tasks_owner ON tasks(owner_id,_order);
UPDATE schema_metadata SET value=6 WHERE key='schema_version';
UPDATE schema_metadata SET value=7 WHERE key='identity_schema_version';
