import { ChevronRight, MoreHorizontal, Plus, X } from 'lucide-react';
import { useEffect, useRef, useState, type ReactNode } from 'react';
import { saveDepartment } from '../api';
import type { DepartmentMembership, ManagedUser, OrganizationDepartment } from '../types';
import './OrganizationControls.css';

export function departmentPath(departments: OrganizationDepartment[], id: string | null): string {
  const names: string[] = [], seen = new Set<string>();
  while (id && !seen.has(id)) { seen.add(id); const d = departments.find(d => d.id === id); if (!d) break; names.unshift(d.name); id = d.parent_id; }
  return names.join(' / ') || '未分配';
}
function subtree(departments: OrganizationDepartment[], id: string): Set<string> {
  const result = new Set([id]);
  for (const current of result) departments.filter(d => d.parent_id === current).forEach(d => result.add(d.id));
  return result;
}
function Popover({ label, children, disabled = false, ariaLabel, radio = false }: { label: ReactNode; children: ReactNode; disabled?: boolean; ariaLabel?: string; radio?: boolean }) {
  const ref = useRef<HTMLDetailsElement>(null);
  useEffect(() => { const close = (event: PointerEvent) => { if (!ref.current?.contains(event.target as Node)) ref.current?.removeAttribute('open'); }; document.addEventListener('pointerdown', close); return () => document.removeEventListener('pointerdown', close); }, []);
  return <details ref={ref} className="org-popover" onKeyDown={e => { if (e.key === 'Escape' && ref.current?.open) { e.stopPropagation(); ref.current.open = false; ref.current.querySelector('summary')?.focus(); } }}><summary aria-label={ariaLabel} aria-disabled={disabled} onClick={e => { if (disabled) e.preventDefault(); }}>{label}</summary><div className="org-popover-content" role={radio ? 'radiogroup' : undefined} aria-label={ariaLabel}>{children}</div></details>;
}
export function DepartmentSelect({ departments, value, onChange, label, disabled = false, allowEmpty = true, emptyLabel = '未分配' }: { departments: OrganizationDepartment[]; value: string | null; onChange: (id: string | null) => void; label: string; disabled?: boolean; allowEmpty?: boolean; emptyLabel?: string }) {
  const options = [...(allowEmpty ? [{ id: '', name: emptyLabel, parent_id: null }] : []), ...departments];
  return <div className="org-field"><span>{label}</span><Popover ariaLabel={label} radio disabled={disabled} label={<><span>{value ? departmentPath(departments, value) : emptyLabel}</span><ChevronRight size={14} /></>}>
    {options.map(d => <button type="button" role="radio" aria-checked={(value || '') === d.id} disabled={disabled} key={d.id} onClick={e => { onChange(d.id || null); const details = e.currentTarget.closest('details'); details?.removeAttribute('open'); details?.querySelector('summary')?.focus(); }}>{d.id ? departmentPath(departments, d.id) : emptyLabel}</button>)}
  </Popover></div>;
}
export function MembershipFields({ departments, value, onChange, disabled = false }: { departments: OrganizationDepartment[]; value: DepartmentMembership; onChange: (value: DepartmentMembership) => void; disabled?: boolean }) {
  return <div className="org-membership-fields"><DepartmentSelect departments={departments} label="主部门" value={value.primary_department_id} disabled={disabled} onChange={id => onChange({ primary_department_id: id, additional_department_ids: id ? value.additional_department_ids.filter(d => d !== id) : [] })} />
    <div className="org-field"><span>兼属部门 <small>选填</small></span><Popover ariaLabel="兼属部门" disabled={disabled || !value.primary_department_id} label={<><span>选择兼属部门</span><ChevronRight size={14} /></>}>
      {departments.filter(d => d.id !== value.primary_department_id).map(d => <label key={d.id}><input type="checkbox" disabled={disabled || !value.primary_department_id} checked={value.additional_department_ids.includes(d.id)} onChange={e => onChange({ ...value, additional_department_ids: e.target.checked ? [...value.additional_department_ids, d.id] : value.additional_department_ids.filter(id => id !== d.id) })} />{departmentPath(departments, d.id)}</label>)}
    </Popover><div className="org-tags">{value.additional_department_ids.map(id => <span key={id}>{departmentPath(departments, id)}<button type="button" disabled={disabled} aria-label={`移除${departmentPath(departments, id)}`} onClick={() => onChange({ ...value, additional_department_ids: value.additional_department_ids.filter(d => d !== id) })}><X size={12} /></button></span>)}</div></div>
  </div>;
}
export function OrganizationDirectory({ departments, users, selectedId, disabled, onSelect, onDepartment, onDelete, renderUser }: { departments: OrganizationDepartment[]; users: ManagedUser[]; selectedId: string; disabled: boolean; onSelect: (id: string) => void; onDepartment: (id: string | null, parent: string | null) => void; onDelete: (id: string) => void; renderUser: (user: ManagedUser, extra: boolean) => ReactNode }) {
  const [collapsed, setCollapsed] = useState<Set<string>>(new Set());
  useEffect(() => { const user = users.find(u => u.id === selectedId); if (!user) return; const reveal = new Set<string>(); for (let id = user.primary_department_id; id && !reveal.has(id); id = departments.find(d => d.id === id)?.parent_id) reveal.add(id); setCollapsed(old => new Set([...old].filter(id => !reveal.has(id)))); }, [selectedId, users, departments]);
  const row = (user: ManagedUser, extra = false) => <div className="org-user-wrap" key={user.id}><button type="button" className={`admin-list-row ${selectedId === user.id ? 'is-active' : ''}`} aria-pressed={selectedId === user.id} disabled={disabled} onClick={() => onSelect(user.id)}>{renderUser(user, extra)}</button></div>;
  const branch = (d: OrganizationDepartment, ancestors = new Set<string>()): ReactNode => { if (ancestors.has(d.id)) return null; const next = new Set([...ancestors, d.id]), ids = subtree(departments, d.id); const count = users.filter(u => [u.primary_department_id, ...(u.additional_department_ids || [])].some(id => id && ids.has(id))).length; const children = departments.filter(x => x.parent_id === d.id), members = users.filter(u => u.primary_department_id === d.id || u.additional_department_ids?.includes(d.id)); return <div className="org-branch" key={d.id}><div className="org-dept-heading"><button type="button" disabled={disabled} className="org-dept-toggle" aria-expanded={!collapsed.has(d.id)} onClick={() => setCollapsed(old => { const result = new Set(old); result.has(d.id) ? result.delete(d.id) : result.add(d.id); return result; })}><ChevronRight size={13} /><strong title={d.name}>{d.name}</strong><small>{count}</small></button><Popover disabled={disabled} label={<span aria-label={`${d.name}更多操作`}><MoreHorizontal size={16} /></span>}><button type="button" disabled={disabled} onClick={e => { e.currentTarget.closest('details')?.removeAttribute('open'); onDepartment(null, d.id); }}>新增子部门</button><button type="button" disabled={disabled} onClick={e => { e.currentTarget.closest('details')?.removeAttribute('open'); onDepartment(d.id, d.parent_id); }}>编辑部门</button><button type="button" className="org-danger" disabled={disabled} onClick={e => { e.currentTarget.closest('details')?.removeAttribute('open'); onDelete(d.id); }}>删除部门</button></Popover></div>{!collapsed.has(d.id) && <div className="org-children">{children.map(child => branch(child, next))}{members.map(u => row(u, u.primary_department_id !== d.id))}{!members.length && !children.length && <p className="org-empty">暂无人员</p>}</div>}</div>; };
  return <div className="admin-list-panel org-directory"><div className="org-directory-heading"><span>账号 · {users.length}</span><button type="button" className="icon-button" aria-label="新增部门" title="新增部门" disabled={disabled} onClick={() => onDepartment(null, null)}><Plus size={15} /></button></div><div className="org-directory-scroll" tabIndex={0} role="region" aria-label="部门与人员列表">{departments.filter(d => !d.parent_id).map(d => branch(d))}{users.some(u => !u.primary_department_id) && <section><h4 className="org-unassigned">未分配</h4>{users.filter(u => !u.primary_department_id).map(u => row(u))}</section>}</div></div>;
}
export function DepartmentEditor({ departments, id, parent, disabled, onDirty, onSaving, onCancel, onSaved }: { departments: OrganizationDepartment[]; id: string | null; parent: string | null; disabled: boolean; onDirty: (value: boolean) => void; onSaving: (value: boolean) => void; onCancel: () => void; onSaved: () => Promise<void> }) {
  const current = departments.find(d => d.id === id), [name, setName] = useState(current?.name || ''), [parentId, setParent] = useState(parent), [error, setError] = useState('');
  const busy = useRef(false), dirty = name !== (current?.name || '') || parent !== parentId;
  useEffect(() => { onDirty(dirty); }, [dirty, onDirty]);
  const excluded = id ? subtree(departments, id) : new Set<string>();
  return <form className="admin-profile-form org-editor" onSubmit={async e => { e.preventDefault(); if (busy.current || disabled || !name.trim()) return; busy.current = true; onSaving(true); setError(''); try { await saveDepartment({ name: name.trim(), parent_id: parentId }, id || undefined); await onSaved(); } catch (error) { setError(error instanceof Error ? error.message : '保存失败，请重试'); } finally { busy.current = false; onSaving(false); } }}><h3>{id ? '编辑部门' : '新增部门'}</h3><p className="admin-profile-form-note">按组织结构设置名称与上级部门。</p><label>部门名称<input required maxLength={100} disabled={disabled} value={name} onChange={e => setName(e.target.value)} placeholder="例如：原料采购组" /></label><DepartmentSelect label="上级部门" departments={departments.filter(d => !excluded.has(d.id))} value={parentId} onChange={setParent} disabled={disabled} emptyLabel="无上级部门" /><p className="admin-profile-form-note">部门调整不改变人员权限；有人员或子部门的部门不可删除。</p>{error && <p className="login-error" role="alert">{error}</p>}<div className="admin-form-actions"><span>{dirty ? '有未保存修改' : ''}</span><button className="secondary-button" type="button" disabled={disabled} onClick={onCancel}>取消</button><button className="primary-button" disabled={disabled || !name.trim() || !!id && !dirty}>{disabled ? '正在保存…' : id ? '保存部门' : '创建部门'}</button></div></form>;
}
