import { ArrowDown, ArrowLeft, ArrowRight, ArrowUp, ArrowUpDown, ChevronLeft, ChevronRight, Columns3, Check, Info, Pencil, Plus, Search, SlidersHorizontal, Trash2, X } from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { fetchJson } from "../api";
import { PriceDateRangeMenu, TrendMaterialMenu } from "./ProcurementWorkbench";
import { moverDateRange } from "./procurementAnalytics";
import { rankCostGaps, priceCents, priceChange, type CostGapDirection } from "./researchAnalytics";
import type { ResearchPage } from "../types";
import p from "./ProcurementWorkbench.module.css";
import s from "./ResearchWorkbench.module.css";

type InputLine = { code: string; kind: "material" | "recipe" | "composite"; ref: string; quantity: string; source_row?: number | null };
type Formula = { id?: string; name?: string; owner?: string; kind?: string; yield: string; lines: InputLine[]; sheet?: string; source_row?: number | null };
type Calculation = { cost: string | null; yield: string; total_input: string; output_quantity: string; missing_materials: string[]; lines: (InputLine & { unit_cost: string | null; amount: string | null; basis: string })[] };
type Graph = { latest: Record<string, Calculation>; inventory: Record<string, Calculation> };
type ComparisonBasis = { record_type?: string; purchase_version?: number; effective_date?: string; latest_cost?: string | null };
type Product = { comparison_basis?: ComparisonBasis | null; lifecycle?: "active" | "draft" | "inactive"; id: string; name: string; owner: string; yield: string; lines: number | InputLine[]; revision: number; has_draft: boolean; status: string; latest_cost: string | null; inventory_cost: string | null; change: { percent: number | null; reason: string }; recorded_at: string; missing_materials: string[]; sheet?: string; source_row?: number | null };
type RecordRow = Product & { latest: Calculation; inventory: Calculation; formula: Formula; graph?: Formula[]; calculations?: Graph; reason?: string; effective_date?: string; record_type?: "formal" | "backfill"; event_id?: string; id: string; product_id?: string };
type Version = { record_type?: "formal" | "backfill"; purchase_version?: number; effective_date?: string; id: string; reason: string; recorded_at: string; products: RecordRow[] };
type Detail = { referenced_by?: {id:string;name:string}[]; product: Product; latest: Calculation | null; inventory: Calculation | null; recipes: Formula[]; calculations?: Graph; draft: { revision: number; formula: Formula; simulation_token?: string } | null; history: RecordRow[]; draft_revision: number; options: { materials: { code: string }[]; recipes: { id: string; name: string }[]; composites: { id: string; name: string }[] } };
type Simulation = { current_latest: Calculation; current_inventory: Calculation; latest: Calculation; inventory: Calculation; affected: { id: string; name: string }[]; simulation_token: string; blocking: string[]; warnings: string[] };
const base = "/api/workbenches/research";
const productPath = (id: string) => `${base}/products/${encodeURIComponent(id)}`;
const request = <T,>(url: string, method: string, body: unknown) => fetchJson<T>(url, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
const labels = { name: "产品内编", owner: "负责人", latest_cost: "产品成本（最新优先）", inventory_cost: "产品成本（库存优先）", change: "价格变化", yield: "收率", lines: "投料明细", status: "状态" };
type Column = keyof typeof labels;
const columns = Object.keys(labels) as Column[];
const cost = (value: string | null | undefined) => priceCents(value) == null ? "—" : `¥${(priceCents(value)! / 100).toLocaleString("zh-CN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const yieldText = (value: string) => `${Number((Number(value) * 100).toFixed(6))}%`;
const date = (value?: string) => value ? new Date(value).toLocaleString("zh-CN", { hour12: false }) : "—";
const formulaVersionLabel = (row: Product) => row.lifecycle === "draft" || !row.revision ? "新配方 · 尚未启用" : `${row.lifecycle === "inactive" ? "已停用 · " : ""}配方 v${row.revision}`;
const lineCount = (row: Product) => Array.isArray(row.lines) ? row.lines.length : row.lines;
const errorText = (error: unknown) => error instanceof Error ? error.message : "操作未完成，请重试。";
const basis: Record<string, string> = { latest: "最新价格", historical_latest: "当期最新价格", current_latest_fallback: "当前最新价格补位", current_inventory_fallback: "当前库存价格补位", inventory: "库存价格", recipe: "引用产品成本", composite: "复配计算成本", missing: "缺少价格" };
function Money({ value, unit = "元/kg" }: { value: string | null | undefined; unit?: string }) { return <strong title={value == null ? "缺少核算价格" : `${cost(value)} ${unit}`}>{cost(value)}</strong>; }
function Movement({ change, comparisonBasis }: { change: Product["change"]; comparisonBasis?: ComparisonBasis | null }) {
  const value = change?.percent;
  const comparisonLabel = comparisonBasis ? `；比较基准：${comparisonBasis.record_type === "backfill" ? `历史回算${comparisonBasis.purchase_version ? ` · 采购 v${comparisonBasis.purchase_version}` : ""}` : "正式成本记录"} ${comparisonBasis.effective_date || ""} · ${cost(comparisonBasis.latest_cost)} 元/kg` : "";
  return <span className={`${s.movement} ${value == null ? s.muted : value > 0 ? s.up : value < 0 ? s.down : s.stable}`} title={`${change?.reason || "最新优先成本与最近一次不同价格比较，金额先四舍五入到两位；相同价格延续上次变化"}${comparisonLabel}${value == null ? "" : `；变化 ${value.toFixed(1)}%`}`}>{value == null ? "暂无对比" : value !== 0 && Math.abs(value) < 0.1 ? `${value > 0 ? "+" : "-"}<0.1%` : `${value > 0 ? "+" : ""}${value.toFixed(1)}%`}</span>;
}
function Status({ row }: { row: Product }) { return <span className={`${s.status} ${row.status !== "ready" ? s.attention : ""}`}>{({ ready: "可核算", missing: "待补价格", updating: "更新中", failed: "更新失败" } as Record<string, string>)[row.status] ?? row.status}{row.has_draft ? " · 有草稿" : ""}</span>; }

export function ResearchWorkbench({ accessLevel, userId, view, page, onPageChange, onEnter }: { accessLevel: number; userId: string; view: "preview" | "full"; page: ResearchPage; onPageChange: (page: ResearchPage) => void; onEnter: () => void }) {
  const [products, setProducts] = useState<Product[] | null>(null);
  const [versions, setVersions] = useState<Version[]>([]);
  const [formulas, setFormulas] = useState<Product[]>([]);
  const [owners, setOwners] = useState<string[]>([]);
  const [pending, setPending] = useState(false);
  const [notice, setNotice] = useState("");
  const [selected, setSelected] = useState<string | null>(null);
  const [versionId, setVersionId] = useState<string | null>(null);
  const [trialsOpen, setTrialsOpen] = useState(false);
  const [jumpFilter, setJumpFilter] = useState("");
  const [loading, setLoading] = useState(true);
  const load = useCallback(async (signal?: AbortSignal) => {
    try {
      const [data, history, catalog] = await Promise.all([fetchJson<{ products: Product[]; pending: boolean }>(`${base}/products`, { signal }), fetchJson<{ versions: Version[] }>(`${base}/history`, { signal }), fetchJson<{ formulas: Product[]; owners: string[] }>(`${base}/formulas`, { signal })]);
      setProducts(data.products); setPending(data.pending); setVersions(history.versions); setFormulas(catalog.formulas); setOwners(catalog.owners); setNotice("");
    } catch (error) { if (!signal?.aborted) setNotice(errorText(error)); }
    finally { if (!signal?.aborted) setLoading(false); }
  }, []);
  useEffect(() => { const controller = new AbortController(); void load(controller.signal); const timer = window.setInterval(() => void load(controller.signal), 10000); return () => { controller.abort(); clearInterval(timer); }; }, [load]);
  const openFilter = (filter: string) => { setJumpFilter(filter); onPageChange(filter === "draft" ? "formulas" : "products"); };
  if (!products) return <article className={`workbench-detail ${s.empty}`}><strong>{loading ? "正在读取产品成本…" : "研发工作台暂时不可用"}</strong>{notice && <p role="alert">{notice}</p>}{!loading && <button className="secondary-button" onClick={() => void load()}>重新加载</button>}</article>;
  return <article className={`workbench-detail ${p.root} ${p.full} ${s.root} ${view === "full" && (page === "products" || page === "formulas") ? s.ledgerPage : ""}`}>
    <header className={p.header}><div><span className={p.eyebrow}>研发五部 · 已启用</span><h1>产品成本计算</h1><p>分别按最新价格、库存价格优先核算原料成本，计入各层收率。</p></div>{view === "preview" ? <button className="primary-button" onClick={onEnter}>进入工作台<ArrowRight size={15}/></button> : null}</header>
    {notice && <div role="alert" className={s.notice}>{notice}<button className="secondary-button" onClick={() => void load()}>重试</button></div>}
    {pending && <div role="status" className={s.notice}>成本正在更新，相关产品暂不标记为最新。完成后自动刷新。</div>}
    {view === "preview" || page === "dashboard" ? <Dashboard products={products} formulas={formulas} versions={versions} onOpen={setSelected} onFilter={openFilter} compact={view === "preview"}/> : page === "products" ? <Ledger products={products} userId={userId} onOpen={setSelected} initialFilter={jumpFilter}/> : page === "formulas" ? <FormulaCatalog initialFilter={jumpFilter} rows={formulas} owners={owners} accessLevel={accessLevel} onOpen={setSelected} onChanged={() => void load()}/> : <History versions={versions} onOpen={setVersionId} onTrials={() => setTrialsOpen(true)}/>}
    {selected && <ProductDrawer id={selected} accessLevel={accessLevel} onClose={() => setSelected(null)} onChanged={() => void load()}/>}
    {versionId && <VersionDrawer id={versionId} onClose={() => setVersionId(null)}/>}
    {trialsOpen && <TrialsDrawer onClose={() => setTrialsOpen(false)}/>}
  </article>;
}

type Period = "14d" | "1m" | "3m" | { start: string; end: string };
const recordDate = (row: { effective_date?: string; recorded_at: string }) => (row.effective_date || row.recorded_at).slice(0, 10);
function useResearchRange(versions: Version[], initial: "14d" | "3m") {
  const [period, setPeriod] = useState<Period>(initial);
  const end = versions.map(recordDate).sort().at(-1) ?? new Date().toISOString().slice(0,10);
  return { period, setPeriod, range: typeof period === "string" ? moverDateRange(end, period) : period };
}
function Dashboard({ products, formulas, versions, onOpen, onFilter, compact }: { products: Product[]; formulas: Product[]; versions: Version[]; onOpen: (id: string) => void; onFilter: (filter: string) => void; compact: boolean }) {
  const [selected, setSelected] = useState(products[0]?.id ?? "");
  const [history, setHistory] = useState<RecordRow[]>([]);
  const [trendError, setTrendError] = useState("");
  const trend = useResearchRange(versions, "3m"), ranking = useResearchRange(versions, "14d");
  useEffect(() => { if (!selected) return; const controller = new AbortController(); setTrendError(""); setHistory([]); fetchJson<Detail>(productPath(selected), { signal: controller.signal }).then(data => setHistory(data.history)).catch(error => { if (!controller.signal.aborted) setTrendError(errorText(error)); }); return () => controller.abort(); }, [selected, versions.map(version => version.id).join("|")]);
  const movements = products.filter(row => row.change?.percent != null && row.change.percent !== 0);
  const missing = products.filter(row => row.status === "missing");
  const warnings = products.filter(row => Number(row.yield) > 1);
  const drafts = formulas.filter(row => row.has_draft || row.lifecycle === "draft");
  const points = [...history].filter(row => recordDate(row) >= trend.range.start && recordDate(row) <= trend.range.end).sort((a,b) => recordDate(a).localeCompare(recordDate(b)) || Number(a.record_type !== "backfill")-Number(b.record_type !== "backfill") || a.recorded_at.localeCompare(b.recorded_at)).map(row => { const latest = priceCents(row.latest_cost), inventory = priceCents(row.inventory_cost); return { time: recordDate(row), latest: latest == null ? null : latest / 100, inventory: inventory == null ? null : inventory / 100, rawLatest: row.latest_cost, rawInventory: row.inventory_cost, backfill: row.record_type === "backfill" }; });
  const [direction, setDirection] = useState("up");
  const rangeMovements = products.flatMap(product => {
    const records = versions.flatMap(version => version.products.filter(row => row.id === product.id).map(row => ({ ...row, effective_date: row.effective_date || version.effective_date, recorded_at: row.recorded_at || version.recorded_at }))).sort((a,b) => recordDate(a).localeCompare(recordDate(b)) || Number(a.record_type !== "backfill")-Number(b.record_type !== "backfill") || a.recorded_at.localeCompare(b.recorded_at));
    const before = records.filter(row => recordDate(row) <= ranking.range.start).at(-1), after = records.filter(row => recordDate(row) <= ranking.range.end).at(-1);
    if (!before || !after) return [];
    const percent = priceChange(after.latest_cost, before.latest_cost);
    if (percent == null) return [];
    return [{ ...product, latest_cost: after.latest_cost, before: before.latest_cost, change: { percent, reason: `${ranking.range.start} 截至成本 ${cost(before.latest_cost)} → ${ranking.range.end} 截至成本 ${cost(after.latest_cost)} 元/kg` } }];
  });
  const ranked = rangeMovements.filter(row => direction === "up" ? row.change.percent > 0 : row.change.percent < 0).sort((a,b) => (direction === "up" ? b.change.percent-a.change.percent : a.change.percent-b.change.percent) || a.name.localeCompare(b.name,"zh-CN",{numeric:true}));
  const movers = ranked.slice(0,10);
  const [gapDirection, setGapDirection] = useState<CostGapDirection>("all");
  const costGaps = rankCostGaps(products, gapDirection);
  return <>
    <div className={s.metrics}><div><span>在用产品</span><strong>{products.length}</strong><small>研发五部完整内编</small></div><div><span>本期成本变动</span><strong>{movements.filter(row => row.change.percent! > 0).length} 涨 / {movements.filter(row => row.change.percent! < 0).length} 降</strong><small>与最近一次不同价格比较</small></div><div><span>待处理事项</span><strong>{new Set([...missing,...warnings,...drafts].map(row => row.id)).size}</strong><small>缺价、收率核对及草稿</small></div><div><span>最近核算</span><strong>{versions.filter(row => row.record_type !== "backfill").length} 期</strong><small>{date(versions.find(row => row.record_type !== "backfill")?.recorded_at)}</small></div></div>
    <div className={`${s.dashboardGrid} ${compact ? s.compactDashboard : ""}`}>
      <section className={s.card}><div className={s.cardHeading}><div><small>产品成本记录 · 含历史回算</small><h2>产品成本趋势</h2></div><div className={p.chartActions}><PriceDateRangeMenu label="成本趋势日期范围" period={trend.period} range={trend.range} onChange={trend.setPeriod}/><TrendMaterialMenu materials={products.map(row => ({id:row.id,code:row.name}))} selected={products.find(row => row.id === selected)?.name ?? ""} onSelect={name => setSelected(products.find(row => row.name === name)?.id ?? selected)} label="趋势产品" placeholder="搜索产品内编"/></div></div>
        {trendError ? <p role="alert">{trendError}</p> : points.length < 2 ? <div className={s.chartEmpty}><strong>{points.length === 1 ? "当前范围仅有一期成本记录" : "当前范围没有成本记录"}</strong><span>可调整日期范围查看其它记录。</span>{points.length === 1 && <span>最新优先 {cost(points[0].rawLatest)} · 库存优先 {cost(points[0].rawInventory)} 元/kg</span>}</div> : <div className={s.chart}><ResponsiveContainer width="100%" height="100%"><LineChart data={points} accessibilityLayer margin={{top:8,right:12,bottom:4,left:0}}><CartesianGrid stroke="#edf0f1" vertical={false}/><XAxis dataKey="time" tick={{fill:"#858d94",fontSize:10}} axisLine={false} tickLine={false} tickFormatter={value => String(value).slice(5).replace("-","/")}/><YAxis tick={{fill:"#858d94",fontSize:10}} axisLine={false} tickLine={false} width={52} tickFormatter={value => Number(value).toFixed(2)}/><Tooltip content={({active,payload}) => { const point = payload?.[0]?.payload as typeof points[number] | undefined; return active && point ? <div className={s.chartTooltip}><strong>{point.time}{point.backfill ? " · 历史回算" : ""}</strong><span>最新优先 <Money value={point.rawLatest}/></span><span>库存优先 <Money value={point.rawInventory}/></span></div> : null; }}/><Line name="最新优先（元/kg）" type="monotone" dataKey="latest" stroke="#2f3337" strokeWidth={2} dot={{r:3,fill:"#fff",strokeWidth:2}} activeDot={{r:4}} connectNulls={false}/><Line name="库存优先（元/kg）" type="monotone" dataKey="inventory" stroke="#708ba4" strokeWidth={2} dot={{r:3,fill:"#fff",strokeWidth:2}} activeDot={{r:4}} connectNulls={false}/></LineChart></ResponsiveContainer></div>}
        <div className={s.trendLegend} aria-label="成本趋势图例">{[{label:"最新优先",color:"#2f3337"},{label:"库存优先",color:"#708ba4"}].map(item => <span key={item.label}><svg width="24" height="12" viewBox="0 0 24 12" aria-hidden="true"><path d="M0 6H24" stroke={item.color} strokeWidth="2"/><circle cx="12" cy="6" r="3" fill="#fff" stroke={item.color} strokeWidth="2"/></svg>{item.label}（元/kg）</span>)}</div>
      </section>
      {!compact && <section className={s.card}><div className={s.cardHeading}><div><small>核算与配方</small><h2>待处理事项</h2></div></div><button className={s.task} onClick={() => onFilter("missing")}><span>缺少核算价格<small>补齐后自动重新核算</small></span><strong>{missing.length}</strong><ChevronRight size={16}/></button><button className={s.task} onClick={() => onFilter("yield")}><span>收率待核对<small>保留原值，核对超过 100% 的收率</small></span><strong>{warnings.length}</strong><ChevronRight size={16}/></button><button className={s.task} onClick={() => onFilter("draft")}><span>待启用草稿<small>由研发管理人员核对后启用</small></span><strong>{drafts.length}</strong><ChevronRight size={16}/></button>{products.some(row => row.status === "failed") && <p role="alert">有成本更新失败，系统将自动重试。</p>}</section>}
      <div className={s.comparisonGrid}>
      <section className={`${s.card} ${s.ranking}`}><div className={s.cardHeading}><div><small>区间首尾 · 最新优先成本</small><h2>产品成本涨跌排行</h2></div><div className={p.chartActions}><PriceDateRangeMenu label="成本排行日期范围" period={ranking.period} range={ranking.range} onChange={ranking.setPeriod}/><div className={p.ledgerMode}><button aria-pressed={direction === "up"} onClick={() => setDirection("up")}>涨幅</button><button aria-pressed={direction === "down"} onClick={() => setDirection("down")}>降幅</button></div></div></div>{movers.length ? <div className={s.rankingColumns}>{[movers.slice(0,5),movers.slice(5,10)].map((group,index) => <div className={s.rankingRows} key={index}>{group.map(row => <button key={row.id} onClick={() => onOpen(row.id)}><span><strong>{row.name}</strong><small title={row.change.reason}>{cost(row.before)} → {cost(row.latest_cost)} 元/kg</small></span><Movement change={row.change}/></button>)}</div>)}</div> : <div className={s.chartEmpty}>当前范围没有可比较的{direction === "up" ? "上涨" : "下降"}记录。</div>}<p className={s.explanation}>本期{direction === "up" ? "上涨" : "下降"} {ranked.length} 项 · 显示前 10 项</p></section>
      <section className={s.card} aria-label="双成本差异排行">
        <div className={s.cardHeading}><div><small>当前成本 · 最新优先 − 库存优先</small><h2>双成本差异排行</h2></div></div>
        <div className={`${p.ledgerMode} ${s.gapSwitch}`} aria-label="差异方向">{([{value:"all",label:"全部"},{value:"latest",label:"最新优先"},{value:"inventory",label:"库存优先"}] as const).map(option => <button key={option.value} aria-pressed={gapDirection === option.value} onClick={() => setGapDirection(option.value)}>{option.label}</button>)}</div>
        {costGaps.length ? <div className={s.gapRows}>{costGaps.slice(0,5).map(row => <button key={row.id} onClick={() => onOpen(row.id)}><span className={s.gapHeading}><strong>{row.name}</strong><strong className={s.gapAmount} title={`最新优先 ${cost(row.latest_cost)} − 库存优先 ${cost(row.inventory_cost)} = ${row.gap.toFixed(2)} 元/kg`}>{row.gap > 0 ? "+" : "−"}¥{Math.abs(row.gap).toLocaleString("zh-CN", {minimumFractionDigits:2,maximumFractionDigits:2})}<small>/kg</small></strong></span><span className={s.gapCosts}><span>最新优先 <Money value={row.latest_cost}/></span><span>库存优先 <Money value={row.inventory_cost}/></span></span></button>)}</div> : <div className={s.chartEmpty}><strong>{gapDirection === "all" ? "当前没有双成本差异" : `暂无${gapDirection === "latest" ? "最新" : "库存"}优先成本较高的产品`}</strong><span>仅比较两种成本均已完成核算的产品。</span></div>}
        <p className={s.explanation}>符合条件 {costGaps.length} 项 · 显示前 5 项<br/>差额单位：元/kg；缺价或更新中的产品不参与。</p>
      </section>
      </div>
    </div>
  </>;
}

function Menu({ title, icon, children, className = "" }: { title: string; icon?: ReactNode; children: ReactNode; className?: string }) {
  const menu = useRef<HTMLDetailsElement>(null);
  const close = (focus = false) => { if (menu.current) menu.current.open = false; if (focus) menu.current?.querySelector("summary")?.focus(); };
  useEffect(() => { const outside = (event: PointerEvent) => { if (!menu.current?.contains(event.target as Node)) close(); }; document.addEventListener("pointerdown",outside); return () => document.removeEventListener("pointerdown",outside); }, []);
  return <details ref={menu} className={`${p.columnMenu} ${className}`} onBlur={event => { if (!event.currentTarget.contains(event.relatedTarget as Node | null)) close(); }} onKeyDown={event => {
    if (event.key === "Escape") { event.preventDefault(); event.stopPropagation(); close(true); }
    if (menu.current?.open && ["ArrowDown","ArrowUp"].includes(event.key) && !(event.target instanceof HTMLInputElement)) { event.preventDefault(); const options = Array.from(menu.current.querySelectorAll<HTMLButtonElement>("button[data-menu-option]")); const index = options.indexOf(document.activeElement as HTMLButtonElement); options[(index + (event.key === "ArrowDown" ? 1 : -1) + options.length) % options.length]?.focus(); }
  }}><summary>{icon}{title}<ChevronRight size={13}/></summary><div>{children}</div></details>;
}
function Options({ options, value, onChange, close = false }: { options: { value: string; label: string }[]; value: string; onChange: (value: string) => void; close?: boolean }) {
  return <div className={p.filterGroup}>{options.map(option => <button type="button" data-menu-option key={option.value} aria-pressed={value === option.value} onClick={event => { onChange(option.value); if (close) { const menu = event.currentTarget.closest("details"); if (menu) { menu.open = false; menu.querySelector("summary")?.focus(); } } }}>{option.label}{value === option.value && <Check size={14}/>}</button>)}</div>;
}
function OwnerMenu({ owners, value, onChange, emptyLabel = "全部负责人" }: { owners: string[]; value: string; onChange: (value: string) => void; emptyLabel?: string }) { return <Menu title={value || emptyLabel} className={p.personMenu}><Options options={[{value:"",label:emptyLabel},...owners.map(owner => ({value:owner,label:owner}))]} value={value} onChange={onChange} close/></Menu>; }

function Ledger({ products, userId, onOpen, initialFilter }: { products: Product[]; userId: string; onOpen: (id: string) => void; initialFilter: string }) {
  const preferenceKey = `research-ledger:${userId}`;
  const [preferences, setPreferences] = useState<{ columns: Column[]; pageSize: number; sort: Column; asc: boolean; sortVersion: number; view: "scroll" | "paged" }>(() => {
    try { const saved = JSON.parse(localStorage.getItem(preferenceKey) || "null"); if (saved) return { columns: columns.filter(key => key === "name" || saved.columns?.includes(key)), pageSize: Number.isInteger(saved.pageSize) && saved.pageSize >= 10 && saved.pageSize <= 200 ? saved.pageSize : 50, sort: saved.sortVersion === 2 && columns.includes(saved.sort) && !["name","owner","status"].includes(saved.sort) ? saved.sort : "change", asc: saved.sortVersion === 2 ? saved.asc === true : false, sortVersion: 2, view: saved.view === "scroll" ? "scroll" : "paged" }; } catch { /* Invalid personal preferences fall back to the confirmed ledger defaults. */ }
    return { columns, pageSize:50, sort:"change", asc:false, sortVersion:2, view:"paged" };
  });
  const [search, setSearch] = useState(""); const [owner, setOwner] = useState(""); const [movement, setMovement] = useState(""); const [status, setStatus] = useState(""); const [draft, setDraft] = useState(""); const [yieldWarning, setYieldWarning] = useState(false); const [page, setPage] = useState(1);
  useEffect(() => { setStatus(initialFilter === "missing" ? "missing" : ""); setDraft(initialFilter === "draft" ? "yes" : ""); setYieldWarning(initialFilter === "yield"); }, [initialFilter]);
  useEffect(() => { try { localStorage.setItem(preferenceKey, JSON.stringify(preferences)); } catch { /* table remains usable when browser storage is unavailable */ } }, [preferenceKey, preferences]);
  useEffect(() => setPage(1), [search,owner,movement,status,draft,yieldWarning,preferences]);
  const filtered = useMemo(() => products.filter(row => (!search || row.name.toLowerCase().includes(search.toLowerCase())) && (!owner || row.owner === owner) && (!status || row.status === status) && (!draft || row.has_draft === (draft === "yes")) && (!yieldWarning || Number(row.yield) > 1) && (!movement || (movement === "none" ? row.change.percent == null : row.change.percent != null && (movement === "up" ? row.change.percent > 0 : movement === "down" ? row.change.percent < 0 : row.change.percent === 0)))).sort((a,b) => {
    const key = preferences.sort; const value = (row: Product): string | number | null => key === "change" ? row.change.percent : key === "lines" ? lineCount(row) : ["latest_cost", "inventory_cost"].includes(key) ? priceCents(row[key as "latest_cost" | "inventory_cost"]) : key === "yield" ? Number(row.yield) : String(row[key]);
    const byName = a.name.localeCompare(b.name,"zh-CN",{numeric:true});
    const av = value(a), bv = value(b); if (av == null || bv == null) return av == null ? bv == null ? byName : 1 : -1;
    return (typeof av === "number" && typeof bv === "number" ? av - bv : String(av).localeCompare(String(bv), "zh-CN", { numeric: true })) * (preferences.asc ? 1 : -1) || byName;
  }), [products, search, owner, movement, status, draft, yieldWarning, preferences]);
  const pages = Math.max(1, Math.ceil(filtered.length/preferences.pageSize)); const current = Math.min(page, pages); const offset = (current-1)*preferences.pageSize;
  const activeFilters = Boolean(owner || movement || status || draft || yieldWarning || search);
  return <section className={s.ledgerSection}><div className={s.sectionHeading}><h2>产品成本</h2><span>{filtered.length} / {products.length} 项 · 元/kg · 含历史回算</span></div><div className={`${p.ledgerTableFrame} ${s.frame}`}><div className={`${p.toolbar} ${s.toolbar}`}>
    <label className={p.searchField}><Search size={15}/><input aria-label="搜索产品内编" value={search} onChange={event => setSearch(event.target.value)} placeholder="搜索产品内编"/></label>
    <OwnerMenu owners={[...new Set(products.map(row => row.owner))].sort()} value={owner} onChange={setOwner}/>
    <Menu title="筛选" icon={<SlidersHorizontal size={14}/>} className={`${p.filterMenu} ${s.filterMenu}`}><span className={p.menuLabel}>价格变化</span><Options options={[{value:"",label:"全部"},{value:"up",label:"上涨"},{value:"down",label:"下降"},{value:"flat",label:"持平"},{value:"none",label:"暂无对比"}]} value={movement} onChange={setMovement}/><span className={p.menuLabel}>核算状态</span><Options options={[{value:"",label:"全部"},{value:"ready",label:"可核算"},{value:"missing",label:"待补价格"},{value:"updating",label:"更新中"},{value:"failed",label:"更新失败"}]} value={status} onChange={setStatus}/><span className={p.menuLabel}>配方草稿</span><Options options={[{value:"",label:"全部"},{value:"yes",label:"有草稿"},{value:"no",label:"无草稿"}]} value={draft} onChange={setDraft}/><label><input type="checkbox" checked={yieldWarning} onChange={event => setYieldWarning(event.target.checked)}/>收率待核对</label></Menu>
    <Menu title="显示" icon={<Columns3 size={14}/>} className={p.displayMenu}><span className={p.menuLabel}>显示字段</span><div className={p.columnGrid}>{columns.map(key => <label key={key}><input type="checkbox" disabled={key === "name"} checked={preferences.columns.includes(key)} onChange={event => setPreferences({...preferences, columns:columns.filter(item => item === key ? event.target.checked : preferences.columns.includes(item))})}/>{labels[key]}</label>)}</div><span className={p.menuLabel}>浏览方式</span><div className={p.ledgerMode}><button aria-pressed={preferences.view === "scroll"} onClick={() => setPreferences({...preferences,view:"scroll"})}>连续</button><button aria-pressed={preferences.view === "paged"} onClick={() => setPreferences({...preferences,view:"paged"})}>分页</button></div>{preferences.view === "paged" && <><span className={p.menuLabel}>每页条数</span><div className={p.pageSizeControl}>{[20,50,100].map(n => <button key={n} aria-pressed={preferences.pageSize === n} onClick={() => setPreferences({...preferences,pageSize:n})}>{n}</button>)}<input key={preferences.pageSize} aria-label="自定义每页条目数" type="number" min="10" max="200" defaultValue={preferences.pageSize} onBlur={event => { const value = Number(event.target.value); if (Number.isInteger(value) && value >= 10 && value <= 200) setPreferences({...preferences,pageSize:value}); else event.target.value = String(preferences.pageSize); }} onKeyDown={event => { if (event.key === "Enter") event.currentTarget.blur(); }}/></div></>}</Menu>
  </div>{activeFilters && <div className={s.filterBar}><span>已筛选 {filtered.length} 项{yieldWarning ? " · 收率待核对" : ""}</span><button onClick={() => { setSearch(""); setOwner(""); setMovement(""); setStatus(""); setDraft(""); setYieldWarning(false); }}>清除筛选</button></div>}
    <div className={`${p.ledgerTableWrap} ${s.tableScroll}`}><table className={`${p.table} ${p.decisionTable} ${s.table}`}><colgroup>{preferences.columns.map(key => <col key={key} style={{width:({name:168,owner:92,latest_cost:182,inventory_cost:182,change:126,yield:90,lines:94,status:114})[key]}}/>)}</colgroup><thead><tr>{preferences.columns.map(key => <th key={key} aria-sort={preferences.sort === key ? preferences.asc ? "ascending" : "descending" : undefined}>{["name","owner","status"].includes(key) ? labels[key] : <button className={s.sort} onClick={() => setPreferences({ ...preferences, sort: key, asc: preferences.sort === key ? !preferences.asc : true })}>{labels[key]}{preferences.sort === key ? preferences.asc ? <ArrowUp size={12}/> : <ArrowDown size={12}/> : <ArrowUpDown size={12}/>}</button>}{key === "change" && <span title="最新优先成本与最近一次不同价格比较，金额先四舍五入到两位；相同价格延续上次变化。首次、缺价或零基数暂无对比。"><Info size={12} aria-label="价格变化说明"/></span>}</th>)}</tr></thead><tbody>{(preferences.view === "scroll" ? filtered : filtered.slice(offset, offset+preferences.pageSize)).map(row => <tr key={row.id}>{preferences.columns.map(key => <td key={key}>{key === "name" ? <button className={s.code} onClick={() => onOpen(row.id)}>{row.name}</button> : key === "latest_cost" || key === "inventory_cost" ? <Money value={row[key]}/> : key === "change" ? <Movement change={row.change} comparisonBasis={row.comparison_basis}/> : key === "yield" ? <span title={Number(row.yield) > 1 ? "原表收率超过100%，请核对" : row.yield}>{yieldText(row.yield)}{Number(row.yield) > 1 ? " · 待核对" : ""}</span> : key === "lines" ? `${lineCount(row)} 条` : key === "status" ? <Status row={row}/> : row.owner}</td>)}</tr>)}{!filtered.length && <tr><td colSpan={preferences.columns.length}><div className={s.empty}>没有符合条件的产品。</div></td></tr>}</tbody></table></div>
    {preferences.view === "paged" && <div className={p.paginationBar}><span>{filtered.length ? offset+1 : 0}–{Math.min(offset+preferences.pageSize,filtered.length)} / {filtered.length} 条</span><button className="icon-button" aria-label="上一页" disabled={current === 1} onClick={() => setPage(current-1)}><ChevronLeft size={15}/></button><span className={s.pageNumber}>第 {current} / {pages} 页</span><button className="icon-button" aria-label="下一页" disabled={current === pages} onClick={() => setPage(current+1)}><ChevronRight size={15}/></button></div>}
  </div></section>;
}

function FormulaCatalog({ rows, owners, accessLevel, onOpen, onChanged, initialFilter = "" }: { rows: Product[]; owners: string[]; accessLevel: number; onOpen: (id: string) => void; onChanged: () => void; initialFilter?: string }) {
  const [search,setSearch] = useState(""), [owner,setOwner] = useState(""), [status,setStatus] = useState(initialFilter === "draft" ? "draft" : "");
  const [creating,setCreating] = useState(false), [name,setName] = useState(""), [newOwner,setNewOwner] = useState(""), [busy,setBusy] = useState(false), [error,setError] = useState("");
  useEffect(() => { setStatus(initialFilter === "draft" ? "draft" : ""); },[initialFilter]);
  const filtered = rows.filter(row => (!search || row.name.toLowerCase().includes(search.toLowerCase())) && (!owner || row.owner === owner) && (!status || (status === "draft" ? row.lifecycle === "draft" || row.has_draft : row.lifecycle === status))).sort((a,b) => a.name.localeCompare(b.name,"zh-CN",{numeric:true}));
  const lifecycle = (row: Product) => row.lifecycle === "inactive" ? "已停用" : row.lifecycle === "draft" ? "待启用" : row.has_draft ? "在用 · 有草稿" : "在用";
  const create = async () => { setBusy(true); setError(""); try { const result = await request<{id:string}>(`${base}/formulas`,"POST",{name:name.trim(),owner:newOwner}); setCreating(false); setName(""); onChanged(); onOpen(result.id); } catch(error) { setError(errorText(error)); } finally { setBusy(false); } };
  return <section className={s.ledgerSection}><div className={s.sectionHeading}><div><h2>配方管理</h2><p className={s.explanation}>维护产品内编与配方，试算后保存草稿，由研发管理人员启用。</p></div>{accessLevel >= 3 && <button className="primary-button" onClick={() => {setCreating(true);setError("");}}><Plus size={15}/>新增配方</button>}</div><div className={`${p.ledgerTableFrame} ${s.frame}`}><div className={`${p.toolbar} ${s.toolbar}`}><label className={p.searchField}><Search size={15}/><input aria-label="搜索配方内编" placeholder="搜索产品内编" value={search} onChange={event => setSearch(event.target.value)}/></label><OwnerMenu owners={owners} value={owner} onChange={setOwner}/><Menu title={({active:"在用",draft:"待启用 / 有草稿",inactive:"已停用"} as Record<string,string>)[status] || "全部状态"} className={p.personMenu}><Options options={[{value:"",label:"全部状态"},{value:"active",label:"在用"},{value:"draft",label:"待启用 / 有草稿"},{value:"inactive",label:"已停用"}]} value={status} onChange={setStatus} close/></Menu></div><div className={`${p.ledgerTableWrap} ${s.tableScroll}`}><table className={`${p.table} ${p.decisionTable} ${s.formulaTable}`}><thead><tr><th>产品内编</th><th>负责人</th><th>收率</th><th>投料明细</th><th>配方版本</th><th>状态</th></tr></thead><tbody>{filtered.map(row => <tr key={row.id}><td><button className={s.code} onClick={() => onOpen(row.id)}>{row.name}</button></td><td>{row.owner}</td><td>{yieldText(row.yield)}</td><td>{lineCount(row)} 条</td><td>{row.revision ? `v${row.revision}` : "尚未启用"}</td><td><span className={`${s.status} ${row.lifecycle !== "active" ? s.attention : ""}`}>{lifecycle(row)}</span></td></tr>)}{!filtered.length && <tr><td colSpan={6}><div className={s.empty}>没有符合条件的配方。</div></td></tr>}</tbody></table></div><div className={p.paginationBar}><span>{filtered.length} / {rows.length} 项</span></div></div>
    {creating && <Drawer title="新增配方" label="先创建内编，再补充投料和收率" onClose={() => setCreating(false)} beforeClose={() => !busy}><form className={s.createForm} onSubmit={event => {event.preventDefault();void create();}}><label>产品内编<input autoFocus required maxLength={200} value={name} onChange={event => setName(event.target.value)} placeholder="填写完整产品内编"/></label><label>负责人</label><OwnerMenu emptyLabel="请选择负责人" owners={owners} value={newOwner} onChange={setNewOwner}/><p className={s.explanation}>新配方只保存为草稿，试算并启用后才进入产品成本台账。</p>{error && <p role="alert" className={s.notice}>{error}</p>}<button className="primary-button" disabled={busy || !name.trim() || !newOwner}>创建草稿并编辑</button></form></Drawer>}
  </section>;
}

function Drawer({ title, label, onClose, beforeClose, children }: { title: string; label: string; onClose: () => void; beforeClose?: () => boolean; children: ReactNode }) {
  const dialog = useRef<HTMLDialogElement>(null); const [closing, setClosing] = useState(false); const timer = useRef<ReturnType<typeof setTimeout> | null>(null);
  useEffect(() => { const previous = document.activeElement as HTMLElement | null; dialog.current?.showModal(); return () => { if (timer.current) clearTimeout(timer.current); previous?.focus({ preventScroll: true }); }; }, []);
  const close = () => { if (timer.current || (beforeClose && !beforeClose())) return; setClosing(true); timer.current = setTimeout(onClose, window.matchMedia("(prefers-reduced-motion: reduce)").matches ? 0 : 140); };
  return <dialog ref={dialog} className={`${s.dialog} ${closing ? s.closing : ""}`} aria-label={title} onCancel={event => { event.preventDefault(); close(); }} onMouseDown={event => { const bounds = event.currentTarget.getBoundingClientRect(); if (event.target === event.currentTarget && (event.clientX < bounds.left || event.clientX > bounds.right || event.clientY < bounds.top || event.clientY > bounds.bottom)) close(); }}><header className={p.drawerHeader}><div><span>{label}</span><h2>{title}</h2></div><button autoFocus className="icon-button" type="button" aria-label="关闭详情" onClick={close}><X size={17}/></button></header><div className={p.drawerBody}>{children}</div></dialog>;
}

function FormulaDetails({ formula, latest, inventory, onRef, policy, onPolicyChange }: { formula: Formula; latest: Calculation | null; inventory: Calculation | null; onRef: (id: string) => void; policy: "latest" | "inventory"; onPolicyChange: (policy: "latest" | "inventory") => void }) {
  const missing = [...new Set([...(latest?.missing_materials ?? []), ...(inventory?.missing_materials ?? [])])];
  if (!latest || !inventory) return <p className={s.notice}>此配方尚未启用，请补充投料并试算。</p>;
  const result = policy === "latest" ? latest : inventory;
  return <><div className={s.dualCosts}><div><span>产品成本 · 最新优先</span><Money value={latest.cost}/><small>元/kg · 缺少最新价时取库存价</small></div><div><span>产品成本 · 库存优先</span><Money value={inventory.cost}/><small>元/kg · 缺少库存价时取最新价</small></div></div>
    {missing.length > 0 && <div role="alert" className={s.notice}>缺少核算价格：{missing.join("、")}。补齐后才能完成核算。</div>}
    {Number(formula.yield) > 1 && <div className={s.notice}>原表收率为 {yieldText(formula.yield)}，已保留原值，请核对。</div>}
    <div className={s.formulaSummary}><span>本层收率 <strong>{yieldText(formula.yield)}</strong></span><span>总投料 <strong title={result.total_input}>{result.total_input} kg</strong></span><span>折合产出 <strong title={result.output_quantity}>{Number(result.output_quantity).toLocaleString("zh-CN", { maximumFractionDigits: 4 })} kg</strong></span></div>
    <div className={s.sectionHeading}><h3>投料明细 · {result.lines.length} 条</h3><div className={p.ledgerMode}><button aria-pressed={policy === "latest"} onClick={() => onPolicyChange("latest")}>最新优先</button><button aria-pressed={policy === "inventory"} onClick={() => onPolicyChange("inventory")}>库存优先</button></div></div>
    <div className={s.detailTable}><table className={p.table}><thead><tr><th>顺序</th><th>投料内编</th><th>数量 / kg</th><th>核算单价 / 元/kg</th><th>取价依据</th><th>金额 / 元</th></tr></thead><tbody>{result.lines.map((line,index) => <tr key={index}><td>{index+1}</td><td>{line.kind !== "material" ? <button className={s.code} onClick={() => onRef(line.ref)}>{line.code}<ChevronRight size={12}/></button> : <strong>{line.code}</strong>}</td><td title={line.quantity}>{line.quantity}</td><td><Money value={line.unit_cost}/></td><td>{basis[line.basis] ?? line.basis}</td><td><Money value={line.amount} unit="元"/></td></tr>)}</tbody></table></div>
    <p className={s.explanation}>本层成本＝投料金额合计 ÷ 总投料量 ÷ 本层收率。引用产品与复配原料沿整条计算链使用相同取价口径。</p>

  </>;
}

function ProductDrawer({ id, accessLevel, onClose, onChanged }: { id: string; accessLevel: number; onClose: () => void; onChanged: () => void }) {
  const [path, setPath] = useState<string[]>([id]); const current = path[path.length-1];
  const [policy, setPolicy] = useState<"latest" | "inventory">("latest");
  const [detail, setDetail] = useState<Detail | null>(null); const [error, setError] = useState(""); const [editing, setEditing] = useState(false); const [dirty, setDirty] = useState(false); const [record, setRecord] = useState<RecordRow | null>(null);
  const [deactivateOpen,setDeactivateOpen] = useState(false), [deactivating,setDeactivating] = useState(false);
  const load = useCallback(async (signal?: AbortSignal, openDraft = false) => { try { setError(""); const result = await fetchJson<Detail>(productPath(current), { signal }); if (!signal?.aborted) { setDetail(result); if (openDraft && result.product.lifecycle === "draft" && accessLevel >= 3) setEditing(true); } } catch (error) { if (!signal?.aborted) setError(errorText(error)); } }, [current, accessLevel]);
  useEffect(() => { const controller = new AbortController(); setDetail(null); setEditing(false); setRecord(null); setDeactivateOpen(false); void load(controller.signal, true); return () => controller.abort(); }, [load]);
  const calculationStatus = detail?.product.status;
  useEffect(() => {
    if (calculationStatus !== "updating" && calculationStatus !== "failed") return;
    const controller = new AbortController();
    let timer: ReturnType<typeof setTimeout>;
    const refresh = async () => { await load(controller.signal); if (!controller.signal.aborted) timer = setTimeout(refresh, 2000); };
    timer = setTimeout(refresh, 2000);
    return () => { controller.abort(); clearTimeout(timer); };
  }, [calculationStatus, load]);
  const allowClose = useCallback(() => !dirty || window.confirm("当前修改尚未保存为草稿，确定放弃这些修改？"), [dirty]);
  useEffect(() => { const leave = (event: Event) => { if (!allowClose()) event.preventDefault(); }; const unload = (event: BeforeUnloadEvent) => { if (dirty) event.preventDefault(); }; window.addEventListener("research-before-leave", leave); window.addEventListener("beforeunload", unload); return () => { window.removeEventListener("research-before-leave", leave); window.removeEventListener("beforeunload", unload); }; }, [allowClose, dirty]);
  const formula = detail?.recipes.find(item => item.id === current) ?? (detail ? { ...detail.product, lines: Array.isArray(detail.product.lines) ? detail.product.lines : [] } : null);
  const deactivate = async () => { if (!detail) return; setDeactivating(true); try { await request(`${productPath(current)}/deactivate`,"POST",{revision:detail.product.revision}); setDeactivateOpen(false); onChanged(); await load(); } catch (reason) { setError(errorText(reason)); } finally { setDeactivating(false); } };
  return <Drawer title={editing ? `编辑配方 · ${detail?.product.name ?? ""}` : detail?.product.name ?? "产品成本"} label={editing ? "试算和草稿不改变正式成本" : "产品配方与成本"} onClose={onClose} beforeClose={allowClose}>
    {error && <p role="alert" className={s.notice}>{error}<button className="secondary-button" onClick={() => void load()}>重试</button></p>}
    {!detail || !formula ? <div className={s.empty}>正在读取配方…</div> : editing ? <Editor detail={detail} formula={formula} accessLevel={accessLevel} onDirty={setDirty} onBack={(force) => { if (force || allowClose()) { setDirty(false); setEditing(false); void load(); } }} onChanged={() => { onChanged(); void load(); }}/>: <>
      <div className={s.sectionHeading}>{path.length > 1 ? <button className={s.back} onClick={() => setPath(path.slice(0,-1))}><ArrowLeft size={15}/>返回上层</button> : <span>{detail.product.owner} · {formulaVersionLabel(detail.product)}</span>}{accessLevel >= 3 && current.startsWith("recipe:") && <button className="secondary-button" onClick={() => setEditing(true)}><Pencil size={14}/>{detail.product.lifecycle === "inactive" ? "恢复并编辑" : detail.draft ? "继续编辑草稿" : "编辑配方"}</button>}</div>
      {(detail.product.status === "updating" || detail.product.status === "failed") && <div className={s.notice}>成本{detail.product.status === "updating" ? "更新中" : "更新失败，等待重试"}。以下为上次完成的有效成本记录。</div>}
      {detail.product.lifecycle === "inactive" && <p className={s.notice}>此配方已停用，不参与当前产品核算。恢复前须重新试算、保存并启用。</p>}
      <FormulaDetails formula={detail.history[0]?.formula ?? formula} latest={detail.latest} inventory={detail.inventory} policy={policy} onPolicyChange={setPolicy} onRef={ref => setPath([...path, ref])}/>
      <section className={s.historySection}><div className={s.sectionHeading}><h3>成本历史</h3><span>{detail.history.length} 条</span></div>{detail.history.map((item,index) => { const expanded = record?.event_id === item.event_id && record?.recorded_at === item.recorded_at; return <div key={`${item.event_id}-${index}`} className={s.inlineRecord}><button className={s.historyRow} aria-expanded={expanded} onClick={() => setRecord(expanded ? null : item)}><span>{recordDate(item)}<small>{item.record_type === "backfill" ? "历史回算 · " : ""}{item.reason ?? "成本核算"}</small></span><Money value={item.latest_cost}/><Movement change={item.change} comparisonBasis={item.comparison_basis}/><ChevronRight size={15} style={{transform:expanded?"rotate(90deg)":undefined}}/></button>{expanded && <div className={s.expandedRecord}><HistoricalFormula record={record!} initialPolicy={policy}/><button className={s.back} onClick={() => setRecord(null)}>收起本期明细</button></div>}</div>; })}{!detail.history.length && <p>尚未建立成本记录。</p>}</section>
      {accessLevel >= 4 && current.startsWith("recipe:") && detail.product.lifecycle === "active" && <section className={s.lifecycleSection}><button className="secondary-button" disabled={deactivating} onClick={() => setDeactivateOpen(!deactivateOpen)}>停用配方</button>{deactivateOpen && <div className={s.confirmation}><h3>核对停用影响</h3><p>停用后将从在用产品及投料选择中移除，历史记录继续保留。恢复须重新试算后启用。</p>{detail.referenced_by?.length ? <p role="alert">仍被在用产品引用，不能停用：{detail.referenced_by.map(row => row.name).join("、")}。</p> : <p>当前没有在用产品引用此配方。</p>}<div className={s.actions}><button className="secondary-button" onClick={() => setDeactivateOpen(false)} disabled={deactivating}>取消</button><button className="primary-button" disabled={deactivating || Boolean(detail.referenced_by?.length)} onClick={() => void deactivate()}>确认停用</button></div></div>}</section>}

    </>}
  </Drawer>;
}

function Editor({ detail, formula: currentFormula, accessLevel, onBack, onChanged, onDirty }: { detail: Detail; formula: Formula; accessLevel: number; onBack: (force?: boolean) => void; onChanged: () => void; onDirty: (value: boolean) => void }) {
  const initial = detail.draft?.formula ?? currentFormula;
  const [formula, setFormula] = useState<Formula>(() => structuredClone(initial));
  const [revision, setRevision] = useState(detail.draft_revision ?? 0);
  const [simulation, setSimulation] = useState<Simulation | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [saved, setSaved] = useState(Boolean(detail.draft)); const [confirming, setConfirming] = useState(false); const [conflict, setConflict] = useState<Detail | null>(null);
  const baseline = useRef(JSON.stringify(initial));
  const dirty = JSON.stringify(formula) !== baseline.current;
  useEffect(() => { onDirty(dirty); }, [dirty, onDirty]);
  const update = (next: Formula) => { setFormula(next); setSimulation(null); setSaved(false); setConfirming(false); setMessage(""); };
  const targets = [...detail.options.materials.map(item => ({ value: `material:${item.code}`, ref: item.code, code: item.code, kind: "material" as const })), ...detail.options.recipes.map(item => ({ value: `recipe:${item.id}`, ref: item.id, code: item.name, kind: "recipe" as const })), ...detail.options.composites.map(item => ({ value: `composite:${item.id}`, ref: item.id, code: item.name, kind: "composite" as const }))].filter(item => item.code !== "CF020C");
  const changeLine = (index: number, value: Partial<InputLine>) => update({ ...formula, lines: formula.lines.map((line,i) => i === index ? { ...line, ...value } : line) });
  const move = (index: number, direction: number) => { const lines = [...formula.lines]; [lines[index], lines[index+direction]] = [lines[index+direction], lines[index]]; update({ ...formula, lines }); };
  const simulate = async () => { setBusy(true); setMessage(""); try { setSimulation(await request<Simulation>(`${productPath(detail.product.id)}/simulate`, "POST", { formula, draft_revision: revision })); setConfirming(false); } catch (error) { setSimulation(null); setMessage(errorText(error)); } finally { setBusy(false); } };
  const save = async () => { if (!simulation) return; setBusy(true); try { const result = await request<{ revision: number; simulation_token: string }>(`${productPath(detail.product.id)}/draft`, "PUT", { formula, draft_revision: revision, simulation_token: simulation.simulation_token }); setRevision(result.revision); setSimulation({ ...simulation, simulation_token: result.simulation_token }); baseline.current = JSON.stringify(formula); onDirty(false); setSaved(true); setMessage("草稿已保存，刷新或重启后可以继续。正式成本保持不变。"); onChanged(); } catch (error) { setMessage(errorText(error)); } finally { setBusy(false); } };
  const discard = async () => { if (!window.confirm("确定放弃已保存的草稿？正式配方不受影响。")) return; setBusy(true); try { await request(`${productPath(detail.product.id)}/draft`, "DELETE", { revision }); onDirty(false); onChanged(); onBack(true); } catch (error) { setMessage(errorText(error)); } finally { setBusy(false); } };
  const activate = async () => { if (!simulation) return; setBusy(true); try { await request(`${productPath(detail.product.id)}/activate`, "POST", { revision, simulation_token: simulation.simulation_token }); onDirty(false); onChanged(); onBack(true); } catch (error) { setConfirming(false); setSimulation(null); setMessage(errorText(error)); } finally { setBusy(false); } };
  const recheck = async () => { setBusy(true); try { setConflict(await fetchJson<Detail>(productPath(detail.product.id))); } catch (error) { setMessage(errorText(error)); } finally { setBusy(false); } };
  const delta = (a: string | null, b: string | null) => { const left = priceCents(a), right = priceCents(b); return left == null || right == null ? "暂无对比" : `${left > right ? "+" : ""}${((left-right)/100).toFixed(2)} 元/kg`; };
  return <div className={s.editor}>
    <div className={s.sectionHeading}><button className={s.back} onClick={() => onBack()} disabled={busy}><ArrowLeft size={15}/>返回产品详情</button><span>{formulaVersionLabel(detail.product)}{detail.draft ? ` · 草稿 r${revision}` : ""}</span></div>
    <p className={s.explanation}>调整投料并试算，保存草稿后由研发管理人员核对启用。原料价格由采购台账提供。</p>
    <fieldset disabled={busy}><label className={s.yieldInput}>本层收率 <input aria-label="本层收率百分比" type="number" min="0.000001" step="any" value={formula.yield === "" ? "" : Number((Number(formula.yield)*100).toFixed(10))} onChange={event => update({ ...formula, yield: event.target.value === "" ? "" : String(Number(event.target.value)/100) })}/><span>%</span></label>
    {Number(formula.yield) > 1 && <p className={s.notice}>收率超过 100%，请核对后再启用；不会自动修改原值。</p>}
    <div className={s.detailTable}><table className={`${p.table} ${s.editTable}`}><thead><tr><th>顺序</th><th>原料 / 引用产品</th><th>投料数量 / kg</th><th>操作</th></tr></thead><tbody>{formula.lines.map((line,index) => <tr key={index}><td>{index+1}</td><td><select aria-label={`第${index+1}项投料`} value={`${line.kind}:${line.ref}`} onChange={event => { const target = targets.find(item => item.value === event.target.value); if (target) changeLine(index, { kind: target.kind, ref: target.ref, code: target.code }); }}>{!targets.some(item => item.value === `${line.kind}:${line.ref}`) && <option value={`${line.kind}:${line.ref}`}>{line.code}（引用待核对）</option>}<optgroup label="研发五部原料">{targets.filter(item => item.kind === "material").map(item => <option key={item.value} value={item.value}>{item.code}</option>)}</optgroup><optgroup label="有效产品">{targets.filter(item => item.kind === "recipe").map(item => <option key={item.value} value={item.value}>{item.code}</option>)}</optgroup><optgroup label="已确认复配">{targets.filter(item => item.kind === "composite").map(item => <option key={item.value} value={item.value}>{item.code}</option>)}</optgroup></select></td><td><input aria-label={`第${index+1}项数量`} type="number" min="0" step="any" value={line.quantity} onChange={event => changeLine(index, { quantity: event.target.value })}/></td><td><div className={s.lineActions}><button className="icon-button" aria-label={`上移第${index+1}项`} disabled={index === 0} onClick={() => move(index,-1)}><ArrowUp size={14}/></button><button className="icon-button" aria-label={`下移第${index+1}项`} disabled={index === formula.lines.length-1} onClick={() => move(index,1)}><ArrowDown size={14}/></button><button className="icon-button" aria-label={`删除第${index+1}项`} onClick={() => update({ ...formula, lines: formula.lines.filter((_,i) => i !== index) })}><Trash2 size={14}/></button></div></td></tr>)}</tbody></table></div>
    <button className="secondary-button" disabled={!targets.length} onClick={() => { const target = targets[0]; update({ ...formula, lines: [...formula.lines, { code: target.code, kind: target.kind, ref: target.ref, quantity: "", source_row: null }] }); }}><Plus size={14}/>添加投料</button></fieldset>
    {message && <div role="status" className={s.notice}>{message}{/草稿已被|草稿已变化|价格或配方已变化|409/.test(message) && <button className="secondary-button" disabled={busy} onClick={() => void recheck()}>保留输入，查看最新版本</button>}</div>}
    {conflict && <section className={s.confirmation}><h3>最新版本已读取，你的输入仍然保留</h3><p>当前{formulaVersionLabel(conflict.product)}，草稿 r{conflict.draft_revision}。</p>{conflict.draft && <details><summary>核对已保存草稿的投料</summary><p>收率 {yieldText(conflict.draft.formula.yield)}</p>{conflict.draft.formula.lines.map((line,index) => <p key={index}>{index+1}. {line.code} · {line.quantity} kg</p>)}</details>}<button className="secondary-button" disabled={busy} onClick={() => { setRevision(conflict.draft_revision); setSimulation(null); setSaved(false); setConflict(null); setMessage("已确认最新版本。请重新试算，再保存你的修改。"); }}>已核对，继续使用我的输入</button></section>}
    {simulation && <section className={s.trialResult}><div className={s.sectionHeading}><h3>双成本试算</h3><span>相对现行配方</span></div><div className={s.dualCosts}><div><span>最新优先</span><Money value={simulation.latest.cost}/><small>{delta(simulation.latest.cost, simulation.current_latest.cost)}</small></div><div><span>库存优先</span><Money value={simulation.inventory.cost}/><small>{delta(simulation.inventory.cost, simulation.current_inventory.cost)}</small></div></div>{simulation.blocking.map((item,index) => <p role="alert" className={s.notice} key={index}>{item}</p>)}{simulation.warnings.map((item,index) => <p className={s.notice} key={index}>{item}</p>)}<p>受影响产品：{simulation.affected.map(item => item.name).join("、") || detail.product.name}</p></section>}
    {confirming && simulation && <section className={s.confirmation} role="region" aria-label="启用最终确认"><h3>确认启用这份配方</h3><p>将启用本页投料与收率，更新 {simulation.affected.length || 1} 个相关产品的成本，并保留旧配方及成本历史。</p><div className={s.confirmDiff}><span>收率：{yieldText(currentFormula.yield)} → {yieldText(formula.yield)}</span><span>投料：{currentFormula.lines.length} 条 → {formula.lines.length} 条</span></div><details><summary>查看最终投料差异</summary>{formula.lines.map((line,index) => { const before = currentFormula.lines[index]; return JSON.stringify(before) === JSON.stringify(line) ? null : <p key={index}>第 {index+1} 项：{before ? `${before.code} ${before.quantity} kg` : "新增"} → {line.code} {line.quantity} kg</p>; })}{currentFormula.lines.slice(formula.lines.length).map((line,index) => <p key={`removed-${index}`}>移除：{line.code} {line.quantity} kg</p>)}</details><p>最新优先 {cost(simulation.latest.cost)}；库存优先 {cost(simulation.inventory.cost)} 元/kg。</p><div className={s.actions}><button className="secondary-button" disabled={busy} onClick={() => setConfirming(false)}>继续核对</button><button className="primary-button" disabled={busy} onClick={() => void activate()}>确认启用</button></div></section>}
    <footer className={s.editorFooter}><button className="secondary-button" disabled={busy} onClick={() => void simulate()}>{busy ? "处理中…" : "试算双成本"}</button><button className="secondary-button" disabled={busy || !simulation} onClick={() => void save()}>保存草稿</button>{(detail.draft || saved) && <button className={s.back} disabled={busy} onClick={() => void discard()}>放弃草稿</button>}{accessLevel >= 4 && <button className="primary-button" disabled={busy || !simulation || !saved || dirty || simulation.blocking.length > 0 || simulation.latest.cost == null || simulation.inventory.cost == null} onClick={() => setConfirming(true)}>核对并启用</button>}</footer>
  </div>;
}

function History({ versions, onOpen, onTrials }: { versions: Version[]; onOpen: (id: string) => void; onTrials: () => void }) {
  const backfill = versions.filter(row => row.record_type === "backfill").length;
  return <section className={s.historySection}><div className={s.sectionHeading}><div><h2>价格历史</h2><p className={s.explanation}>查看各期产品成本、涨跌及取价依据；历史回算与正式记录分别标明。</p></div><button className="secondary-button" onClick={onTrials}>历史试算</button></div><div className={s.historySummary}><span>全部记录 <strong>{versions.length} 期</strong></span><span>正式记录 <strong>{versions.length-backfill} 期</strong></span><span>历史回算 <strong>{backfill} 期</strong></span></div><ol className={`${p.historyTimeline} ${s.researchTimeline}`}>{versions.map((version,index) => {
    const changed = version.products.filter(row => row.change?.percent != null); const up = changed.filter(row => row.change.percent! > 0).length, down = changed.filter(row => row.change.percent! < 0).length, stable = changed.filter(row => row.change.percent === 0).length;
    return <li key={version.id}><i/><button onClick={() => onOpen(version.id)}><span className={p.historyDate}><strong>{recordDate(version)}</strong>{index === 0 && <em>最新记录</em>}</span><span className={p.historySource}><strong>{version.record_type === "backfill" ? `采购 v${version.purchase_version ?? "—"} · 历史回算` : "正式成本记录"}</strong><small title={version.reason}>{version.reason}</small></span><span className={p.historyBatchStats}><span>{version.products.length} 项</span><span className={p.historyUp}>↑ {up}</span><span className={p.historyDown}>↓ {down}</span><span className={p.historyStable}>持平 {stable}</span>{changed.length < version.products.length && <span>暂无对比 {version.products.length-changed.length}</span>}</span><ChevronRight size={16}/></button></li>;
  })}</ol>{!versions.length && <div className={s.empty}>正在建立第一期成本基线。</div>}</section>;
}

function HistoricalFormula({ record, initialPolicy = "latest" }: { record: RecordRow; initialPolicy?: "latest" | "inventory" }) {
  const [policy, setPolicy] = useState<"latest" | "inventory">(initialPolicy);
  const rootId = record.product_id ?? record.formula.id ?? record.id;
  const [path, setPath] = useState([rootId]); const current = path[path.length-1];
  const formula = current === rootId ? record.formula : record.graph?.find(item => item.id === current);
  const latest = current === rootId ? record.latest : record.calculations?.latest[current];
  const inventory = current === rootId ? record.inventory : record.calculations?.inventory[current];
  return <>{path.length > 1 && <button className={s.back} onClick={() => setPath(path.slice(0,-1))}><ArrowLeft size={15}/>返回上层</button>}{formula && latest && inventory ? <><h3>{formula.name}</h3><FormulaDetails formula={formula} latest={latest} inventory={inventory} policy={policy} onPolicyChange={setPolicy} onRef={ref => setPath([...path,ref])}/></> : <p className={s.notice}>该历史记录没有保存此引用的明细。</p>}</>;
}
function VersionDrawer({ id, onClose }: { id: string; onClose: () => void }) {
  const [version, setVersion] = useState<Version | null>(null); const [error, setError] = useState(""); const [record, setRecord] = useState<RecordRow | null>(null);
  useEffect(() => { const controller = new AbortController(); fetchJson<Version>(`${base}/history/${encodeURIComponent(id)}`, { signal: controller.signal }).then(setVersion).catch(error => { if (!controller.signal.aborted) setError(errorText(error)); }); return () => controller.abort(); }, [id]);
  return <Drawer title={record?.name ?? (version?.record_type === "backfill" ? `采购 v${version.purchase_version ?? "—"} · 历史回算` : "正式成本版本")} label={version ? recordDate(version) : "价格历史"} onClose={onClose}>{error ? <p role="alert">{error}</p> : !version ? <p>正在读取历史…</p> : record ? <><button className={s.back} onClick={() => setRecord(null)}><ArrowLeft size={14}/>返回版本明细</button><HistoricalFormula record={record}/></> : <><div className={s.historySummary}><span>成本日期 <strong>{recordDate(version)}</strong></span><span>产品 <strong>{version.products.length} 项</strong></span><span>{version.record_type === "backfill" ? "历史回算" : "正式记录"}</span></div><p className={s.explanation}>{version.reason}</p><p className={s.explanation}>记录时间：{date(version.recorded_at)}{version.record_type === "backfill" ? "。按当期采购价格回算；当期缺价时使用的当前补位价在投料依据中标明。" : ""}</p><div className={s.detailTable}><table className={p.table}><thead><tr><th>产品内编</th><th>最新优先 / 元/kg</th><th>库存优先 / 元/kg</th><th>价格变化</th></tr></thead><tbody>{version.products.map((row,index) => <tr key={`${row.id}-${index}`}><td><button className={s.code} onClick={() => setRecord(row)}>{row.name}</button></td><td><Money value={row.latest_cost}/></td><td><Money value={row.inventory_cost}/></td><td><Movement change={row.change}/></td></tr>)}</tbody></table></div></>}</Drawer>;
}
function TrialsDrawer({ onClose }: { onClose: () => void }) {
  const [recipes, setRecipes] = useState<(Formula & { latest: Calculation })[] | null>(null); const [selected, setSelected] = useState<number | null>(null); const [error, setError] = useState("");
  useEffect(() => { const controller = new AbortController(); fetchJson<{ recipes: (Formula & { latest: Calculation })[] }>(`${base}/trials`, { signal: controller.signal }).then(data => setRecipes(data.recipes)).catch(error => { if (!controller.signal.aborted) setError(errorText(error)); }); return () => controller.abort(); }, []);
  const recipe = selected == null ? null : recipes?.[selected];
  return <Drawer title="历史试算" label="原表留存 · 不参与当前核算" onClose={onClose}><p className={s.explanation}>以下三组旧试算按原表保留，仅供追溯；当前使用已确认的 CF401B 复配方案。</p>{error && <p role="alert">{error}</p>}{!recipes ? <p>正在读取原表试算…</p> : recipe ? <><button className={s.back} onClick={() => setSelected(null)}><ArrowLeft size={15}/>返回试算列表</button><h3>{recipe.name}</h3><p>原表试算成本：<Money value={recipe.latest.cost}/> 元/kg · 收率 {yieldText(recipe.yield)}</p><div className={s.detailTable}><table className={p.table}><thead><tr><th>顺序</th><th>投料</th><th>数量 / kg</th><th>原表单价</th></tr></thead><tbody>{recipe.latest.lines.map((line,index) => <tr key={index}><td>{index+1}</td><td>{line.code}</td><td>{line.quantity}</td><td><Money value={line.unit_cost}/></td></tr>)}</tbody></table></div><p className={s.explanation}>{recipe.sheet} · 原表第 {recipe.source_row} 行</p></> : recipes.map((item,index) => <button key={item.id} className={s.historyRow} onClick={() => setSelected(index)}><span>{item.name}<small>{item.sheet} · 第 {item.source_row} 行</small></span><ChevronRight size={15}/></button>)}</Drawer>;
}
