import {useState} from "react";
import {ArrowLeft, GripVertical, Check, Info, Plus, Trash2, ChevronRight} from "lucide-react";
import {DecimalInput} from "../components/DecimalInput";
import {FormFooter} from "../components/WorkbenchLayout";
import {Switch} from "../components/Switch";
import {DiscardChangesDialog} from "../components/Interaction";
import {ReasonFields, OwnerMenu, Menu, Options, Money, CostSource} from "./ResearchProductView";
import {type Adjustment, type Detail, type Formula, formulaVersionLabel, yieldText, cost} from "./researchModel";
import {priceCents} from "./researchAnalytics";
import {useResearchEditSession} from "./researchEditSession";
import p from "../components/WorkbenchSurface.module.css";
import s from "./ResearchWorkbench.module.css";
export function ResearchFormulaEditor(props: {onBusy:(busy:boolean)=>void;adjustment:Adjustment;detail:Detail;formula:Formula;accessLevel:number;onBack:(force?:boolean)=>void;onChanged:()=>void;onDirty:(value:boolean)=>void}) {
 const {detail,formula:currentFormula,onBack}=props;
 const {formula,revision,simulation,pendingAction,busy,message,saved,confirming,conflict,dirty,trialUpdating,liveTrial,update,changeLine,changeAmount,move,simulate,save,cancelTrial,discard,activate,recheck,acceptConflict,cancelSaveOpen,setCancelSaveOpen,setConfirming}=useResearchEditSession(props);
 const ratioBase=Number(formula.ratio_base);
 const [dragRow,setDragRow]=useState<number|null>(null),[dropRow,setDropRow]=useState<number|null>(null);
  const targets = [...detail.options.materials.map(item => ({ value: `material:${item.code}`, ref: item.code, code: item.code, kind: "material" as const })), ...detail.options.recipes.map(item => ({ value: `recipe:${item.id}`, ref: item.id, code: item.name, kind: "recipe" as const })), ...detail.options.composites.map(item => ({ value: `composite:${item.id}`, ref: item.id, code: item.name, kind: "composite" as const }))].filter(item => item.code !== "CF020C");
  const delta = (a: string | null, b: string | null) => { const left = priceCents(a), right = priceCents(b); return left == null || right == null ? "暂无对比" : `${left > right ? "+" : ""}${((left-right)/100).toFixed(2)} 元/kg`; };
  return <div className={s.editor}>
    <div className={s.sectionHeading}><button className={s.back} onClick={() => onBack()} disabled={busy}><ArrowLeft size={15}/>返回产品详情</button><span>{formulaVersionLabel(detail.product)}{detail.draft ? ` · 草稿 r${revision}` : ""}</span></div>
    <p className={s.explanation}>调整投料并试算，保存草稿后由有启用权的人员核对启用。原料价格由采购台账提供。</p>
    <fieldset disabled={busy || (saved && !dirty)} inert={busy || (saved && !dirty)} className={saved && !dirty ? s.lockedFields : undefined}>
    {!(detail.product.lifecycle === "draft" && detail.product.revision === 0) && <ReasonFields value={formula} onChange={value => update({...formula,...value})}/>}
    <div className={s.formulaSettings}>
      <div className={s.ownerSetting}><span>负责人</span><OwnerMenu owners={detail.options.owners ?? []} value={formula.owner ?? ""} emptyLabel="请选择负责人" onChange={owner => update({...formula,owner})}/></div>
      <div className={s.yieldSetting}><label className={s.yieldInput}>收率 <DecimalInput aria-label="收率百分比" type="number" min="0.000001" step="any" value={formula.yield === "" ? "" : Number((Number(formula.yield)*100).toFixed(10))} onChange={event => update({ ...formula, yield: event.target.value === "" ? "" : String(Number(event.target.value)/100) })}/><span>%</span></label></div>
      <div className={s.linkSetting}><strong id="formula-link-label">自动换算</strong><button className={`access-policy-help ${s.linkHelp}`} type="button" aria-label="查看自动换算说明"><Info size={14}/><span role="tooltip" id="formula-link-help">{formula.ratio_linked ? `基准 ${formula.ratio_base} kg · 配方比例与实际投料双向同步` : "独立填写，成本按实际投料核算"}</span></button><Switch type="button" role="switch" className="settings-mode-switch" aria-labelledby="formula-link-label" aria-describedby="formula-link-help" aria-checked={formula.ratio_linked ?? true} onClick={() => update({ ...formula, ratio_linked: !formula.ratio_linked, lines: !formula.ratio_linked ? formula.lines.map(line => ({ ...line, ratio: line.quantity.trim() ? (Number(line.quantity) / ratioBase * 100).toFixed(2) : "" })) : formula.lines })}><span /></Switch></div>
    </div>
    <div className={s.costSettings}>{(["latest", "inventory"] as const).map(policy => <div key={policy}><label>{policy === "latest" ? "最新优先成本" : "库存优先成本"}</label><div className={p.ledgerMode}><button type="button" aria-pressed={formula.manual_costs?.[policy] == null} onClick={() => update({...formula,manual_costs:{...formula.manual_costs,[policy]:null}})}>自动核算</button><button type="button" aria-pressed={formula.manual_costs?.[policy] != null} onClick={() => update({...formula,manual_costs:{...formula.manual_costs,[policy]:formula.manual_costs?.[policy] ?? simulation?.[policy].cost ?? detail[policy]?.cost ?? ""}})}>手动指定</button></div>{formula.manual_costs?.[policy] != null && <label className={s.manualInput}><DecimalInput aria-label={`${policy === "latest" ? "最新" : "库存"}优先手动成本`} type="number" min="0" step="any" value={formula.manual_costs[policy] ?? ""} onChange={event => update({...formula,manual_costs:{...formula.manual_costs,[policy]:event.target.value}})}/><span>元/kg</span></label>}</div>)}</div>
    <div className={s.inputHeading}><h3>投料明细 <span>{formula.lines.length} 项</span></h3><span>比例合计允许超过 100%</span></div>
    {Number(formula.yield) > 1 && <p className={s.notice}>收率超过 100%，请核对后再启用；不会自动修改原值。</p>}
    <div className={s.detailTable}><table className={`${p.table} ${s.editTable}`}><thead><tr><th>顺序</th><th>原料 / 引用产品</th><th>配方比例</th><th>实际投料 / kg</th><th>操作</th></tr></thead><tbody>{formula.lines.map((line,index) => <tr key={index} data-input-row={index} className={dropRow === index && dragRow !== index ? s.dropRow : undefined}><td><button type="button" className={s.dragHandle} aria-label={`拖动第${index+1}项排序`} title="拖动调整顺序，也可用上下方向键移动" onKeyDown={event => { if (event.key === "ArrowUp" || event.key === "ArrowDown") { event.preventDefault(); move(index, index + (event.key === "ArrowUp" ? -1 : 1)); } }} onPointerDown={event => { if (event.button !== 0) return; event.currentTarget.setPointerCapture(event.pointerId); setDragRow(index); setDropRow(index); }} onPointerMove={event => { if (!event.currentTarget.hasPointerCapture(event.pointerId)) return; const row = document.elementFromPoint(event.clientX, event.clientY)?.closest("tr[data-input-row]"); if (row && event.currentTarget.closest("tbody")?.contains(row)) setDropRow(Number(row.getAttribute("data-input-row"))); }} onPointerUp={event => { if (event.currentTarget.hasPointerCapture(event.pointerId)) { event.currentTarget.releasePointerCapture(event.pointerId); if (dropRow != null) move(index, dropRow); } setDragRow(null); setDropRow(null); }} onPointerCancel={() => { setDragRow(null); setDropRow(null); }}><GripVertical size={14}/><span>{index+1}</span></button></td><td><Menu title={line.code || "选择投料"} className={s.inputMenu}>{(["material", "recipe", "composite"] as const).map(kind => <div key={kind}><span className={s.inputGroupLabel}>{{material:"研发五部原料",recipe:"有效产品",composite:"已确认复配"}[kind]}</span><Options options={targets.filter(item => item.kind === kind).map(item => ({value:item.value,label:item.code}))} value={`${line.kind}:${line.ref}`} onChange={value => { const target = targets.find(item => item.value === value); if (target) changeLine(index, {kind:target.kind,ref:target.ref,code:target.code}); }} close/></div>)}</Menu></td><td><DecimalInput aria-label={`第${index+1}项配方比例`} type="number" min="0" step="any" value={line.ratio ?? ""} onChange={event => changeAmount(index, "ratio", event.target.value)}/><span> %</span></td><td><DecimalInput aria-label={`第${index+1}项数量`} type="number" min="0" step="any" value={line.quantity} onChange={event => changeAmount(index, "quantity", event.target.value)}/></td><td><div className={s.lineActions}><button className="icon-button" aria-label={`删除第${index+1}项`} onClick={() => update({ ...formula, lines: formula.lines.filter((_,i) => i !== index) })}><Trash2 size={14}/></button></div></td></tr>)}</tbody></table></div>
    <button className="secondary-button" disabled={!targets.length} onClick={() => { const target = targets[0]; update({ ...formula, lines: [...formula.lines, { code: target.code, kind: target.kind, ref: target.ref, quantity: "", ratio: "", source_row: null }] }); }}><Plus size={14}/>添加投料</button></fieldset>
    {message && <div role="status" className={s.notice}>{message}{/草稿已被|草稿已变化|价格或配方已变化|409/.test(message) && <button className="secondary-button" disabled={busy} onClick={() => void recheck()}>保留输入，查看最新版本</button>}</div>}
    {conflict && <section className={s.confirmation}><h3>最新版本已读取，你的输入仍然保留</h3><p>当前{formulaVersionLabel(conflict.product)}，草稿 r{conflict.draft_revision}。</p>{conflict.draft && <details><summary>核对已保存草稿的投料</summary><p>收率 {yieldText(conflict.draft.formula.yield)}</p>{conflict.draft.formula.lines.map((line,index) => <p key={index}>{index+1}. {line.code} · {line.quantity} kg</p>)}</details>}<button className="secondary-button" disabled={busy} onClick={() => { acceptConflict(); }}>已核对，继续使用我的输入</button></section>}
    {simulation && <section className={s.trialResult}><div className={s.sectionHeading}><h3>双成本试算</h3><span aria-live="polite">{trialUpdating ? "正在更新 · 下方为上次结果" : "相对现行配方"}</span></div><div className={s.dualCosts}><div><span>最新优先</span><Money value={simulation.latest.cost}/><CostSource result={simulation.latest}/><small>{delta(simulation.latest.cost, simulation.current_latest.cost)}</small></div><div><span>库存优先</span><Money value={simulation.inventory.cost}/><CostSource result={simulation.inventory}/><small>{delta(simulation.inventory.cost, simulation.current_inventory.cost)}</small></div></div>{simulation.blocking.map((item,index) => <p role="alert" className={s.notice} key={index}>{item}</p>)}{simulation.warnings.map((item,index) => <p className={s.notice} key={index}>{item}</p>)}<div className={s.impactScope}><span>启用后影响范围</span>{simulation.affected.every(item => item.id === detail.product.id) ? <span>仅当前产品 <strong>{detail.product.name}</strong></span> : <details><summary><span>涉及 <strong>{simulation.affected.length}</strong> 个产品</span><span>查看内编 <ChevronRight size={14}/></span></summary><ul>{simulation.affected.map(item => <li key={item.id}><strong>{item.name}</strong>{item.id === detail.product.id && <small>当前产品</small>}</li>)}</ul></details>}</div></section>}
    {confirming && simulation && <section className={s.confirmation} role="region" aria-label="启用最终确认"><h3>确认启用这份配方</h3><p>{detail.product.revision === 0 ? "操作" : "调整原因"}：{formula.adjustment_reason}{formula.adjustment_note && ` · ${formula.adjustment_note}`}</p><p>将启用本页投料与收率，更新 {simulation.affected.length || 1} 个相关产品的成本，并保留旧配方及成本历史。</p><div className={s.confirmDiff}><span>收率：{yieldText(currentFormula.yield)} → {yieldText(formula.yield)}</span><span>投料：{currentFormula.lines.length} 条 → {formula.lines.length} 条</span></div><details><summary>查看最终投料差异</summary>{formula.lines.map((line,index) => { const before = currentFormula.lines[index]; return JSON.stringify(before) === JSON.stringify(line) ? null : <p key={index}>第 {index+1} 项：{before ? `${before.code} ${before.quantity} kg` : "新增"} → {line.code} {line.quantity} kg</p>; })}{currentFormula.lines.slice(formula.lines.length).map((line,index) => <p key={`removed-${index}`}>移除：{line.code} {line.quantity} kg</p>)}</details><div className={s.confirmDiff}>{(["latest", "inventory"] as const).map(policy => <span key={policy}>{policy === "latest" ? "最新优先" : "库存优先"} · {simulation[policy].cost_source === "manual" ? "手动指定" : "自动核算"}：{cost(simulation[policy === "latest" ? "current_latest" : "current_inventory"].cost)} → {cost(simulation[policy].cost)} 元/kg<CostSource result={simulation[policy]}/></span>)}</div><div className={s.actions}><button className="secondary-button" disabled={busy} onClick={() => setConfirming(false)}>继续核对</button><button className="primary-button" disabled={busy} onClick={() => void activate()}>确认启用</button></div></section>}
    {cancelSaveOpen && <DiscardChangesDialog title="取消保存的草稿？" description="将撤销已保存草稿并关闭试算结果，当前填写保留在本页，可重新试算和保存。正式配方和成本保持不变。" cancelLabel="保留草稿" confirmLabel="取消保存" disabled={busy} onCancel={() => setCancelSaveOpen(false)} onDiscard={() => void discard()}/>}
    <FormFooter className={s.editorFooter} status={<div role="status" className={saved && !dirty && !pendingAction && !trialUpdating ? s.savedState : s.footerStatus}>{saved && !dirty && !pendingAction && !trialUpdating && <Check size={14}/>}{trialUpdating ? "正在更新试算，完成后可保存" : pendingAction ? ({simulate:"正在试算…",save:"正在保存草稿…",discard:"正在放弃草稿…",activate:"正在启用…",recheck:"正在读取最新版本…"}[pendingAction]) : !simulation ? (saved ? "草稿已保存，试算后可继续核对" : "修改完成后，先试算成本") : !saved || dirty ? "试算完成，可保存草稿" : simulation.blocking.length || simulation.latest.cost == null || simulation.inventory.cost == null ? "草稿已保存，请处理试算提示后启用" : Boolean(detail.capabilities?.can_activate) ? "草稿已保存，可核对并启用" : "草稿已保存，待有启用权的人员核对启用"}</div>}>
          {!(saved && !dirty && (simulation || trialUpdating || liveTrial.current)) && <button className={!simulation ? "primary-button" : "secondary-button"} disabled={busy} onClick={() => simulation || trialUpdating || liveTrial.current ? cancelTrial() : void simulate()}>{pendingAction === "simulate" ? "试算中…" : simulation || trialUpdating || liveTrial.current ? "取消试算" : "试算双成本"}</button>}
          {saved && !dirty ? <button className={`secondary-button ${s.dangerButton}`} disabled={busy || trialUpdating} onClick={() => setCancelSaveOpen(true)}>取消保存</button> : <button className={simulation ? "primary-button" : "secondary-button"} disabled={busy || trialUpdating || !simulation} onClick={() => void save()}>{pendingAction === "save" ? "保存中…" : "保存草稿"}</button>}
          {Boolean(detail.capabilities?.can_activate) && <button className={simulation && saved && !dirty && !simulation.blocking.length && simulation.latest.cost != null && simulation.inventory.cost != null ? "primary-button" : "secondary-button"} disabled={busy || trialUpdating || !simulation || !saved || dirty || simulation.blocking.length > 0 || simulation.latest.cost == null || simulation.inventory.cost == null || confirming} onClick={() => setConfirming(true)}>{pendingAction === "activate" ? "启用中…" : confirming ? "请核对上方确认内容" : "核对并启用"}</button>}
    </FormFooter>
  </div>;
}
