import assert from 'node:assert/strict';
import {createServer} from 'vite';
import react from '@vitejs/plugin-react';
import {chromium} from 'playwright';
import {mkdirSync, readFileSync, writeFileSync} from 'node:fs';
import path from 'node:path';

// No production proxy: pytest supplies an authenticated synthetic API on a random port.
const api = new URL(process.env.W8_TEST_API ?? '');
assert.equal(api.hostname, '127.0.0.1');
assert.ok(api.port && api.port !== '8000' && process.env.W8_TEST_PASSWORD);
const red = process.env.W8_RED ?? '';
const output = process.env.W8_OUTPUT_DIR ?? `.scratch/w8-20261003/${red ? 'red-' + red : 'browser'}`;
mkdirSync(output, {recursive:true});
const entry = path.resolve('w8-app.tsx').replaceAll('\\', '/');
const original = new Set(['App.tsx','screens/WorkbenchScreen.tsx','components/Sidebar.tsx','components/SettingsDialog.tsx','components/FeedbackDialog.tsx','workbenches/WorkbenchModuleSlot.tsx']);
const server = await createServer({configFile:false,logLevel:'silent',cacheDir:'.scratch/w8-20261003/vite-cache',plugins:[react(),{
 name:'w8-isolated-app',enforce:'pre',
 configureServer(instance){instance.middlewares.use(async(req,res,next)=>{
  const url=req.url.split('?')[0];
  if(url.startsWith('/api/')){res.statusCode=503;res.end('Isolated interception required');return;}
  if(url!=='/w8-app' && url!=='/w8-login')return next();
  res.setHeader('Content-Type','text/html');res.end(await instance.transformIndexHtml(url,`<html><body><div id="root"></div><script type="module" src="${url==='/w8-login'?'/src/main.tsx':'/w8-app.tsx'}"></script></body></html>`));
 });},
 resolveId(id){if(id==='/w8-app.tsx'||id===entry)return entry;},
 load(id){
  const relative=path.relative(path.resolve('src'),id).replaceAll('\\','/');
  if(red && original.has(relative))return readFileSync(`.scratch/w8-20261003/before/src/${relative}`,'utf8');
  if(id===entry)return `import {createElement as h,useState} from 'react';import {createRoot} from 'react-dom/client';import App from '/src/App';import {WorkbenchModuleSlot} from '/src/workbenches/WorkbenchModuleSlot';import '/src/styles.css';
function Host({initial}){const [user,setUser]=useState(initial);window.w8User=setUser;if(new URLSearchParams(location.search).has('denied'))return h(WorkbenchModuleSlot,{workbenchId:'management',title:'示例',currentUser:user,view:'full',salesPage:'dashboard',researchPage:'dashboard',procurementPage:'dashboard',onSalesPageChange:()=>{},onResearchPageChange:()=>{},onProcurementPageChange:()=>{},onEnter:()=>{}});return h(App,{currentUser:user,onUserChanged:setUser,onLogout:async()=>{await fetch('/api/logout',{method:'POST'});location.href='/w8-login'},onPasswordChanged:()=>{}})}
fetch('/api/me').then(r=>r.json()).then(initial=>{const root=createRoot(document.getElementById('root'));window.w8Unmount=()=>root.unmount();root.render(h(Host,{initial}));});`;
 },
 transform(code,id){
  // Executable example is mounted ONLY by this isolated server, at the unregistered slot.
  if(id.replaceAll('\\','/').endsWith('/src/workbenches/WorkbenchModuleSlot.tsx'))return code.replace('import { WorkbenchLoading }',`import {StaticWorkbenchExample} from '/previews/components/StaticWorkbenchExample';
const readExample = signal => window.w8ExampleRead(signal);
import { WorkbenchLoading }`).replace(': <Pending title={props.title} />',': window.w8ExampleRead ? <StaticWorkbenchExample accessLevel={accessLevel} view={props.view} onEnter={props.onEnter} read={readExample}/> : <Pending title={props.title} />');
 }
}],server:{host:'127.0.0.1',port:0,hmr:false}});
const gate=()=>{let release;const promise=new Promise(resolve=>{release=resolve});return {promise,release}};
const evidence=[];let browser;
try{
 await server.listen();browser=await chromium.launch({headless:true});const origin=server.resolvedUrls.local[0];
 async function run(name,fault,check){
  if(red && name!==({search:'search-clears-old-opened-workbench',boundary:'module-failure-switch-and-real-reload',feedback:'feedback-latest-list-wins',identity:'identity-key-clears-draft-and-old-unread'})[red])return;
  const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();page.setDefaultTimeout(10000);
  if(fault==='unread-slow')await page.addInitScript(()=>{const start=window.setInterval.bind(window),stop=window.clearInterval.bind(window);window.w8Intervals=new Map();window.setInterval=(...args)=>{const id=start(...args);if(new Error().stack.includes("appFeedback"))window.w8Intervals.set(id,args[1]);return id};window.clearInterval=id=>{window.w8Intervals.delete(id);return stop(id)}});
  const unreadInitial=fault==='unread-failed'?page.waitForResponse(r=>new URL(r.url()).pathname==='/api/feedback/unread'):null;
  const pending=gate(),held=gate(),errors=[],requests=[],network=[];let closing=false,injected=false,feedbackReads=0,unreadReads=0;
  page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)network.push(`${r.status()} ${new URL(r.url()).pathname}`)});
  const send=async(url,data,method='POST',status=200)=>{const r=await context.request.fetch(new URL(url,api).href,{method,data});assert.equal(r.status(),status,await r.text());return status===204?null:r.json()};
  const get=async url=>{const r=await context.request.get(new URL(url,api).href);assert.equal(r.status(),200,await r.text());return r.json()};
  const login=async(name='test-admin')=>send('/api/login',{username:name,password:process.env.W8_TEST_PASSWORD});
  assert.equal((await get('/api/health')).environment,'test');
  const initial=await login(fault==='readonly'?'w8-viewer':fault==='none'?'w8-none':'test-admin');
  if(fault.startsWith('demo'))await page.addInitScript(()=>{let n=0;window.w8ExampleRead=signal=>new Promise((resolve,reject)=>{const timer=setTimeout(()=>{if(++n===1)reject(new Error('隔离示例读取失败'));else resolve('合成示例数据')},100);signal.addEventListener('abort',()=>{clearTimeout(timer);reject(new DOMException('Aborted','AbortError'))},{once:true})})});
  await page.route('**/*',async route=>{const req=route.request(),url=new URL(req.url());try{
   assert.equal(url.origin,new URL(origin).origin);
   if(fault==='chunk' && url.pathname==='/src/workbenches/ProcurementWorkbench.tsx'&&!injected){injected=true;return route.abort('failed');}
   if(!url.pathname.startsWith('/api/'))return route.continue();
   requests.push({path:url.pathname,method:req.method(),body:req.postData()?req.postDataJSON():null});
   if(url.pathname==='/api/feedback/unread')unreadReads++;
   if(url.pathname==='/api/feedback'&&req.method()==='GET')feedbackReads++;
   if(['modules-failed','benches-failed'].includes(fault)&&url.pathname===(fault==='modules-failed'?'/api/modules':'/api/workbenches')&&!injected){injected=true;return route.fulfill({status:503,json:{detail:'W8 合成状态读取失败'}})}
   if(fault==='unread-failed'&&url.pathname==='/api/feedback/unread'&&!injected){injected=true;return route.fulfill({status:503,json:{detail:'W8 合成未读失败'}})}
   if(fault==='feedback-failed'&&url.pathname==='/api/feedback'&&req.method()==='POST'&&!injected){injected=true;return route.fulfill({status:500,json:{detail:'W8 合成提交失败'}})}
   if(fault==='read-late'&&url.pathname.endsWith('/read')&&!injected){injected=true;held.release();await pending.promise;return route.fulfill({status:503,json:{detail:'W8 合成已读失败'}})}
   const delayedWrite = fault==='quote-busy' && url.pathname==='/api/workbenches/sales/batches' && req.method()==='POST' || fault==='procurement-busy' && url.pathname.endsWith('/prices/bulk-adjustments') && req.method()==='POST' || fault==='research-busy' && url.pathname.endsWith('/draft') && req.method()==='PUT';
   if(delayedWrite){held.release();await pending.promise;return route.fulfill({status:503,json:{detail:'W8 合成忙碌写入失败'}})}
   if(fault.startsWith('background-') && url.pathname===(fault==='background-modules'?'/api/modules':'/api/workbenches') && requests.filter(r=>r.path===url.pathname).length===2)return route.fulfill({status:503,json:{detail:'W8 合成后台状态失败'}});
   if(fault==='list-late'&&url.pathname==='/api/feedback'&&req.method()==='GET'&&feedbackReads===2){held.release();await pending.promise;return route.fulfill({status:503,json:{detail:'W8 旧列表失败'}})}
   if(fault==='retry-late'&&url.pathname==='/api/feedback'&&req.method()==='GET'){if(feedbackReads===1)return route.fulfill({status:503,json:{detail:'W8 首次列表失败'}});if(feedbackReads===2){held.release();await pending.promise;return route.fulfill({status:503,json:{detail:'W8 旧重试失败'}})}}
   // Forward the browser's same-origin request to the isolated API origin, preserving CSRF validation.
   if(fault==='import-busy'&&url.pathname.endsWith('/import-preview')){held.release();await pending.promise;return route.fulfill({status:503,json:{detail:'W8 合成导入检查失败'}})}
   if(fault==='import-write-busy'&&url.pathname==='/api/workbenches/procurement/imports'&&req.method()==='POST'){held.release();await pending.promise;return route.fulfill({status:503,json:{detail:'W8 合成导入写回失败'}})}
   if(fault==='publish-busy'&&url.pathname.endsWith('/publish')){held.release();await pending.promise;return route.fulfill({status:503,json:{detail:'W8 合成启用失败'}})}
   const response=await route.fetch({url:new URL(url.pathname+url.search,api).href,headers:{...req.headers(),origin:api.origin}});
   // A synthetic pending overview exercises the actual publish dialog without creating a business update.
   if(fault==='publish-busy'&&url.pathname==='/api/workbenches/procurement/overview'){
    const data=await response.json(),material=data.materials.find(row=>row.code==='A');
    const item={material_id:material.id,code:material.code,name:material.name,unit:material.unit,published_price:material.published_price,draft_price:'31',change:0.03,comparison_basis:'published'};
    const update={id:'w8-isolated-update',price_date:'2026-10-03',source_name:'W8 合成启用状态',status:'draft',created_at:'2026-10-03T00:00:00Z',updated_at:'2026-10-03T00:00:00Z',submitted_at:null,return_reason:null,activate_at:null,created_by_name:'W8 合成',submitted_by_name:null,summary:{coverage_count:data.materials.length,changed_count:1,unchanged_count:0,error_count:0,risk_count:0},items:[item],input_items:[item],issues:[],events:[]};
    return route.fulfill({status:200,json:{...data,current_update:update,capabilities:{...data.capabilities,can_activate:true}}});
   }
   if(url.pathname==='/api/workbenches'&&['prototype','unregistered','demo','demo-none'].includes(fault))return route.fulfill({status:200,json:[{id:'management',mode:fault==='prototype'?'prototype':'active'}]});
   if(fault==='demo-none'&&url.pathname==='/api/me'){const user=await response.json();return route.fulfill({status:200,json:{...user,is_system_admin:false,scope_levels:{}}})}
   const hold=(fault==='list-order'&&url.pathname==='/api/feedback'&&req.method()==='GET'&&feedbackReads===1)||(fault==='feedback-unmount'&&url.pathname==='/api/feedback'&&req.method()==='POST')||(fault==='unread-slow'&&url.pathname==='/api/feedback/unread'&&!injected)||(fault==='identity'&&url.pathname==='/api/feedback/unread'&&!injected)||(fault==='calculator-busy'&&url.pathname.endsWith('/calculator/saved')&&req.method()==='POST');
   if(hold){injected=true;held.release();await pending.promise;}
   await route.fulfill({response});
  }catch(error){if(!closing&&!req.failure())errors.push(error.message)}});
  try{
   await page.goto(origin+(fault==='login'? 'w8-login':fault==='demo-none'?'w8-app?denied':'w8-app'));await check({page,context,get,send,login,initial,pending,held,requests,unreadInitial,unreadReads:()=>unreadReads});
   assert.deepEqual(errors,[]);
   await page.screenshot({path:`${output}/${name}.png`,fullPage:true});evidence.push({name,status:'passed',requests:requests.filter(r=>r.method!=='GET'),milliseconds:Math.round(performance.now()-started)});
  }catch(error){await page.screenshot({path:`${output}/${name}-failed.png`,fullPage:true});writeFileSync(`${output}/${name}-failed.txt`,await page.locator('body').innerText());writeFileSync(`${output}/${name}-failed-diagnostics.json`,JSON.stringify({errors,network,requests},null,2));throw error;}
  finally{closing=true;pending.release();await context.close();}
 }
 let started;
 const scenario=async(...args)=>{started=performance.now();await run(...args)};
 const nav=page=>page.getByRole('navigation',{name:'主要导航'});
 async function enter(page,title){await page.getByRole('button').filter({hasText:title}).filter({has:page.locator('em')}).click();await page.getByRole('button',{name:'进入工作台',exact:true}).click();}
 async function feedback(page){await page.getByRole('button',{name:/^意见反馈/}).click();await page.getByRole('dialog',{name:/用户反馈|我的反馈|新建反馈/}).waitFor();}
 async function cancel(page){await page.getByRole('alertdialog').getByRole('button',{name:'继续编辑',exact:true}).click();}
 async function search(page,text){await page.locator('.sidebar__search').evaluate(el=>el.click());await page.getByRole('textbox',{name:'搜索全部内容'}).fill(text);await page.locator('.global-search__results button').first().click();}
 await scenario('search-clears-old-opened-workbench','',async({page})=>{await enter(page,'原料价格管理');await search(page,'产品报价管理');await page.getByRole('button',{name:'进入工作台',exact:true}).waitFor();assert.equal(await page.locator('.workspace-layout.is-module-open').count(),0);assert.ok((await page.locator('.screen-header__title>strong').innerText()).startsWith('工作台'));assert.equal(await page.getByRole('button',{name:'采购看板',exact:true}).count(),0);await search(page,'产品成本计算');await page.getByRole('button',{name:'进入工作台',exact:true}).waitFor();});
 await scenario('module-failure-switch-and-real-reload','chunk',async({page})=>{await page.getByText(/原料价格管理加载失败/).waitFor();await page.getByRole('button').filter({hasText:'产品成本计算'}).filter({has:page.locator('em')}).click();await page.getByRole('button',{name:'进入工作台',exact:true}).waitFor();await page.getByRole('button').filter({hasText:'原料价格管理'}).filter({has:page.locator('em')}).click();await page.getByRole('button',{name:'重新加载页面',exact:true}).click();await page.getByRole('button',{name:'进入工作台',exact:true}).waitFor();assert.equal(await page.getByRole('alert').filter({hasText:'加载失败'}).count(),0);});
 await scenario('module-status-failure-reload-recovers','modules-failed',async({page})=>{await page.getByText('模块状态不可用',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'进入工作台',exact:true}).count(),0);await page.getByRole('button',{name:'重新加载页面',exact:true}).click();await page.getByRole('button',{name:'进入工作台',exact:true}).waitFor();});
 await scenario('workbench-status-failure-reload-recovers','benches-failed',async({page})=>{await page.getByText('模块状态不可用',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'进入工作台',exact:true}).count(),0);await page.getByRole('button',{name:'重新加载页面',exact:true}).click();await page.getByRole('button',{name:'进入工作台',exact:true}).waitFor();});
 await scenario('prototype-stays-explicit-example','prototype',async({page,requests})=>{await page.getByText('当前为界面与业务结构原型，页面数值均为示例数据。',{exact:true}).waitFor();assert.equal(requests.filter(r=>r.path.startsWith('/api/workbenches/')).length,0);assert.equal(await page.getByRole('button',{name:'进入工作台',exact:true}).count(),0);});
 await scenario('active-unregistered-stays-protected','unregistered',async({page,requests})=>{await page.getByText('经营数据分析已进入受保护接入状态',{exact:true}).waitFor();assert.equal(await page.getByText('¥486 万',{exact:true}).count(),0);assert.equal(requests.filter(r=>r.path.startsWith('/api/workbenches/')).length,0);});
 await scenario('off-and-no-scope-hide-real-modules','none',async({page,requests})=>{await page.getByText('暂无可用模块',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'进入工作台',exact:true}).count(),0);assert.equal(requests.filter(r=>r.path.startsWith('/api/workbenches/')).length,0);});
 await scenario('readonly-real-research-entry','readonly',async({page})=>{await enter(page,'产品成本计算');await page.getByRole('button',{name:'产品成本',exact:true}).click();await page.getByRole('button',{name:'K172-C',exact:true}).first().click();await page.getByRole('dialog',{name:'K172-C',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'编辑配方',exact:true}).count(),0);assert.equal(await page.getByRole('button').filter({hasText:'原料价格管理'}).filter({has:page.locator('em')}).count(),0);});
 await scenario('actual-login-logout-clears-session-draft','login',async({page})=>{await feedback(page);await page.getByRole('button',{name:'新建反馈',exact:true}).click();await page.getByLabel('反馈内容',{exact:true}).fill('W8 登录草稿');await page.getByRole('button',{name:'关闭反馈',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});await page.locator('.profile-trigger').click();await page.getByRole('menuitem',{name:'退出登录',exact:true}).click();await page.getByRole('textbox',{name:'用户名'}).fill('w8-none');await page.getByLabel('密码',{exact:true}).fill(process.env.W8_TEST_PASSWORD);await page.getByRole('button',{name:'登录',exact:true}).click();await feedback(page);await page.getByRole('button',{name:'新建反馈',exact:true}).click();assert.equal(await page.getByLabel('反馈内容',{exact:true}).inputValue(),'');});
 await scenario('identity-key-clears-draft-and-old-unread','identity',async({page,held,pending,initial,login})=>{await held.promise;await feedback(page);await page.getByRole('button',{name:'新建反馈',exact:true}).click();await page.getByLabel('反馈内容',{exact:true}).fill('W8 旧身份草稿');const next=await login('w8-none');await page.evaluate(user=>window.w8User(user),next);pending.release();await page.getByText('暂无可用模块',{exact:true}).waitFor();await feedback(page);await page.getByRole('button',{name:'新建反馈',exact:true}).click();assert.equal(await page.getByLabel('反馈内容',{exact:true}).inputValue(),'');assert.notEqual(initial.id,next.id);});
 await scenario('same-user-profile-keeps-editor-scope-refreshes-registry','',async({page,initial,requests})=>{await enter(page,'原料价格管理');await page.getByRole('button',{name:'原料价格',exact:true}).click();await page.getByRole('button',{name:'编辑价格',exact:true}).click();await page.getByRole('textbox',{name:'搜索原料',exact:true}).fill('A');await page.getByRole('textbox',{name:'A待发布价',exact:true}).fill('31');await page.evaluate(user=>window.w8User({...user,display_name:'W8 改名'}),initial);assert.equal(await page.getByRole('textbox',{name:'A待发布价',exact:true}).inputValue(),'31');const n=requests.filter(r=>r.path==='/api/workbenches').length;await page.evaluate(user=>window.w8User({...user,scope_levels:{...user.scope_levels,management:2}}),initial);await page.waitForFunction(()=>document.querySelector('input[aria-label="A待发布价"]')?.value==='31');await page.waitForTimeout(200);assert.ok(requests.filter(r=>r.path==='/api/workbenches').length>n);assert.equal(await page.getByRole('textbox',{name:'A待发布价',exact:true}).inputValue(),'31');});
 await scenario('quotation-app-search-section-logout-cancel-and-unmount','',async({page,requests})=>{await enter(page,'产品报价管理');await page.getByRole('button',{name:'产品报价',exact:true}).click();await page.getByRole('button',{name:'K172-C',exact:true}).click();await page.getByRole('button',{name:'开始报价',exact:true}).click();await page.getByLabel('客户名称',{exact:true}).fill('W8 保留报价');await nav(page).getByRole('button',{name:'新聊天',exact:true}).evaluate(el=>el.click());await cancel(page);assert.equal(await page.getByLabel('客户名称',{exact:true}).inputValue(),'W8 保留报价');await page.getByRole('button',{name:'全局搜索',exact:true}).evaluate(el=>el.click());await page.getByRole('textbox',{name:'搜索全部内容'}).fill('原料价格管理');await page.locator('.global-search__results button').first().click();await cancel(page);assert.equal(await page.getByLabel('客户名称',{exact:true}).inputValue(),'W8 保留报价');await page.locator('.profile-trigger').evaluate(el=>el.click());await page.getByRole('menuitem',{name:'退出登录',exact:true}).evaluate(el=>el.click());await cancel(page);assert.equal(requests.filter(r=>r.path==='/api/logout').length,0);await nav(page).getByRole('button',{name:'返回主页',exact:true}).evaluate(el=>el.click());await page.getByRole('alertdialog').getByRole('button',{name:'放弃修改',exact:true}).click();await page.getByRole('button',{name:'进入工作台',exact:true}).waitFor();assert.equal(await page.getByLabel('客户名称',{exact:true}).count(),0);});
 await scenario('calculator-app-busy-and-cancel-preserve-input','calculator-busy',async({page,held,pending})=>{await enter(page,'产品报价管理');await page.getByRole('button',{name:'测算工具',exact:true}).click();await page.getByRole('button',{name:'手工成本',exact:true}).click();const input=page.getByRole('textbox',{name:'手工产品成本'});await input.fill('4');await page.getByRole('button',{name:'保存对比',exact:true}).click();await held.promise;await nav(page).getByRole('button',{name:'新聊天',exact:true}).click();assert.equal(await input.inputValue(),'4');assert.equal(await page.getByRole('alertdialog').count(),0);pending.release();await page.getByRole('button',{name:'保存对比',exact:true}).waitFor();await input.fill('9');await page.getByRole('button',{name:'产品报价',exact:true}).click();await cancel(page);assert.equal(await input.inputValue(),'9');});
 await scenario('procurement-app-section-search-cancel-preserve-input','',async({page})=>{await enter(page,'原料价格管理');await page.getByRole('button',{name:'原料价格',exact:true}).click();await page.getByRole('button',{name:'编辑价格',exact:true}).click();await page.getByRole('textbox',{name:'搜索原料',exact:true}).fill('A');const input=page.getByRole('textbox',{name:'A待发布价',exact:true});await input.fill('31');await nav(page).getByRole('button',{name:'新聊天',exact:true}).click();await cancel(page);assert.equal(await input.inputValue(),'31');await search(page,'产品成本计算');await cancel(page);assert.equal(await input.inputValue(),'31');});
 await scenario('research-same-product-editor-keeps-input-on-editable-level-change','',async({page,initial,requests})=>{
  await enter(page,'产品成本计算');await page.getByRole('button',{name:'产品成本',exact:true}).click();await page.getByRole('button',{name:'K172-C',exact:true}).first().click();await page.getByRole('button',{name:'编辑配方',exact:true}).click();
  const reason=page.getByRole('alertdialog',{name:'记录调整原因'});await reason.getByRole('button',{name:'配方优化',exact:true}).click();await reason.getByRole('button',{name:'进入编辑',exact:true}).click();
  const input=page.getByRole('spinbutton',{name:'收率百分比'});await input.fill('95');const original=await input.elementHandle();
  for(const research of [3,4]){const refreshed=Promise.all([page.waitForResponse(r=>new URL(r.url()).pathname==='/api/workbenches'&&r.status()===200),page.waitForResponse(r=>decodeURIComponent(new URL(r.url()).pathname)==='/api/workbenches/research/products/recipe:K172-C'&&r.status()===200)]);await page.evaluate(({user,research})=>window.w8User({...user,is_system_admin:false,scope_levels:{procurement:4,sales:4,research}}),{user:initial,research});await refreshed;assert.equal(await original.evaluate(el=>el.isConnected),true);assert.equal(await input.inputValue(),'95');}
  await page.getByRole('button',{name:'原料价格',exact:true}).evaluate(el=>el.click());await cancel(page);assert.equal(await input.inputValue(),'95');assert.equal(requests.filter(r=>r.method!=='GET').length,0);
 });
 await scenario('research-app-page-search-cancel-and-pending-cleanup','',async({page})=>{await enter(page,'产品成本计算');await page.getByRole('button',{name:'产品成本',exact:true}).click();await page.getByRole('button',{name:'K172-C',exact:true}).first().click();await page.getByRole('button',{name:'编辑配方',exact:true}).click();const reason=page.getByRole('alertdialog',{name:'记录调整原因'});await reason.getByRole('button',{name:'配方优化',exact:true}).click();await reason.getByRole('button',{name:'进入编辑',exact:true}).click();await page.getByRole('spinbutton',{name:'收率百分比'}).fill('95');await page.getByRole('button',{name:'原料价格',exact:true}).evaluate(el=>el.click());await cancel(page);assert.equal(await page.getByRole('spinbutton',{name:'收率百分比'}).inputValue(),'95');await search(page,'产品报价管理');await cancel(page);assert.equal(await page.getByRole('spinbutton',{name:'收率百分比'}).inputValue(),'95');await nav(page).getByRole('button',{name:'新聊天',exact:true}).evaluate(el=>el.click());await page.getByRole('alertdialog',{name:'放弃未保存的修改？'}).waitFor();await page.evaluate(()=>window.w8Unmount());assert.equal(await page.getByRole('alertdialog').count(),0);});
 await scenario('feedback-close-reopen-error-retry-and-context','feedback-failed',async({page,requests})=>{await enter(page,'产品报价管理');await page.getByRole('button',{name:'测算工具',exact:true}).click();await feedback(page);await page.getByRole('button',{name:'新建反馈',exact:true}).click();await page.getByLabel('反馈内容',{exact:true}).fill('W8 反馈保留');await page.getByRole('button',{name:'关闭反馈',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});await feedback(page);assert.equal(await page.getByLabel('反馈内容',{exact:true}).inputValue(),'W8 反馈保留');await page.getByRole('button',{name:'提交反馈',exact:true}).click();await page.getByText('W8 合成提交失败',{exact:true}).waitFor();assert.equal(await page.getByLabel('反馈内容',{exact:true}).inputValue(),'W8 反馈保留');await page.getByRole('button',{name:'提交反馈',exact:true}).click();await page.getByText('反馈已提交，处理结果会在这里通知你。',{exact:true}).waitFor();assert.equal(requests.filter(r=>r.path==='/api/feedback'&&r.method==='POST').at(-1).body.context,'产品报价管理 / 测算工具');});
 await scenario('feedback-latest-list-wins','list-order',async({page,get,send,held,pending})=>{await feedback(page);await held.promise;await send('/api/feedback',{kind:'功能建议',text:'W8 最新列表'});await page.getByRole('button',{name:'新建反馈',exact:true}).click();await page.getByRole('button',{name:'返回列表',exact:true}).first().click();await page.getByRole('button').filter({hasText:'W8 最新列表'}).waitFor();pending.release();await page.waitForTimeout(200);assert.equal(await page.getByRole('button').filter({hasText:'W8 最新列表'}).count(),1);assert.ok((await get('/api/feedback')).some(r=>r.text==='W8 最新列表'));});
 await scenario('feedback-committed-old-save-cannot-clear-new-identity-draft','feedback-unmount',async({page,held,pending,login})=>{await feedback(page);await page.getByRole('button',{name:'新建反馈',exact:true}).click();await page.getByLabel('反馈内容',{exact:true}).fill('W8 已提交旧反馈');await page.getByRole('button',{name:'提交反馈',exact:true}).click();await held.promise;const next=await login('w8-none');await page.evaluate(user=>window.w8User(user),next);await feedback(page);await page.getByRole('button',{name:'新建反馈',exact:true}).click();await page.getByLabel('反馈内容',{exact:true}).fill('W8 新身份输入');pending.release();await page.waitForTimeout(200);assert.equal(await page.getByLabel('反馈内容',{exact:true}).inputValue(),'W8 新身份输入');});
 await scenario('feedback-late-read-error-does-not-contaminate-next-view','read-late',async({page,send,login,held,pending})=>{await login('w8-none');await send('/api/feedback',{kind:'问题反馈',text:'W8 未读消息'});await login();await feedback(page);await page.getByRole('button').filter({hasText:'W8 未读消息'}).click();await held.promise;await page.getByRole('button',{name:'返回列表',exact:true}).first().click();await page.getByRole('button',{name:'新建反馈',exact:true}).click();pending.release();await page.waitForTimeout(200);assert.equal(await page.getByText('未能标记已读，消息提醒已保留。',{exact:true}).count(),0);});
 await scenario('feedback-unread-singleflight-hidden-focus-and-unmount','unread-slow',async({page,held,pending,unreadReads})=>{await held.promise;await page.evaluate(()=>{for(let i=0;i<8;i++)window.dispatchEvent(new Event('focus'))});await page.waitForTimeout(100);assert.equal(unreadReads(),1);const first=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/feedback/unread');pending.release();await (await first).finished();await page.waitForTimeout(100);await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));window.dispatchEvent(new Event('focus'))});await page.waitForTimeout(100);assert.equal(unreadReads(),1);await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:false});document.dispatchEvent(new Event('visibilitychange'))});await page.waitForTimeout(150);assert.equal(unreadReads(),2);await page.waitForTimeout(30500);assert.equal(unreadReads(),3);assert.equal(await page.evaluate(()=>[...window.w8Intervals.values()].filter(delay=>delay===30000).length),1);await page.evaluate(()=>window.w8Unmount());await page.waitForFunction(()=>[...window.w8Intervals.values()].filter(delay=>delay===30000).length===0);await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await page.waitForTimeout(100);assert.equal(unreadReads(),3);});
 await scenario('feedback-unread-failure-is-unknown-and-focus-recovers','unread-failed',async({page,unreadInitial})=>{await (await unreadInitial).finished();await page.getByRole('button',{name:'意见反馈',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'意见反馈',exact:true}).getAttribute('title'),'意见反馈 · 未读状态暂不可用');await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await page.waitForFunction(()=>[...document.querySelectorAll('button')].some(button=>button.title==='意见反馈'));assert.equal(await page.getByRole('button',{name:/^意见反馈/}).getAttribute('title'),'意见反馈');});
 await scenario('isolated-static-example-load-retry-preview-dirty-busy-and-exit','demo',async({page,requests})=>{await page.getByText('隔离示例读取失败',{exact:false}).waitFor();await page.getByRole('button',{name:'重试',exact:true}).click();await page.getByRole('button',{name:'进入示例',exact:true}).click();const input=page.getByLabel('示例输入',{exact:true});await input.fill('合成草稿');await nav(page).getByRole('button',{name:'新聊天',exact:true}).click();await cancel(page);assert.equal(await input.inputValue(),'合成草稿');await page.getByRole('button',{name:'切换示例忙碌状态',exact:true}).click();await nav(page).getByRole('button',{name:'新聊天',exact:true}).click();assert.equal(await page.getByText('示例正在处理',{exact:true}).count(),1);await page.getByRole('button',{name:'切换示例忙碌状态',exact:true}).click();await nav(page).getByRole('button',{name:'新聊天',exact:true}).click();await page.getByRole('alertdialog').getByRole('button',{name:'放弃修改',exact:true}).click();assert.equal(await input.count(),0);assert.equal(requests.filter(r=>r.path.startsWith('/api/workbenches/')).length,0);});
 await scenario('isolated-static-example-access-denied','demo-none',async({page,requests})=>{await page.getByText('暂无示例查看权限',{exact:true}).waitFor();assert.equal(await page.getByLabel('示例输入',{exact:true}).count(),0);assert.equal(requests.filter(r=>r.path.startsWith('/api/workbenches/')).length,0);});
 for(const registry of ['modules','benches'])await scenario('background-'+registry+'-failure-retains-draft-and-retry','background-'+registry,async({page,initial})=>{await enter(page,'原料价格管理');await page.getByRole('button',{name:'原料价格',exact:true}).click();await page.getByRole('button',{name:'编辑价格',exact:true}).click();await page.getByRole('textbox',{name:'搜索原料',exact:true}).fill('A');const input=page.getByRole('textbox',{name:'A待发布价',exact:true});await input.fill('31');await page.evaluate(user=>window.w8User({...user,scope_levels:{...user.scope_levels,management:2}}),initial);await page.getByText('状态刷新失败，当前保留上次确认的入口和未保存输入。',{exact:false}).waitFor();assert.equal(await input.inputValue(),'31');await page.getByRole('button',{name:'重试',exact:true}).click();await page.getByText('状态刷新失败，当前保留上次确认的入口和未保存输入。',{exact:false}).waitFor({state:'hidden'});assert.equal(await input.inputValue(),'31');});
 await scenario('settings-account-toggle-keeps-unsaved-permissions','',async({page})=>{await page.locator('.profile-trigger').click();await page.getByRole('menuitem',{name:/系统设置/}).click();await page.getByRole('button',{name:'用户管理',exact:true}).click();await page.getByRole('button').filter({hasText:'W8 合成查看者'}).click();await page.getByRole('button',{name:'职能工作台',exact:true}).click();const scope=page.getByRole('group',{name:'研发工作台业务权限'});await scope.getByRole('button',{name:'编辑',exact:true}).click();await page.getByRole('button',{name:'停用账号',exact:true}).click();await page.getByText('账号已停用',{exact:true}).waitFor();assert.equal(await scope.getByRole('button',{name:'编辑',exact:true}).getAttribute('aria-pressed'),'true');await page.getByRole('button',{name:'启用账号',exact:true}).click();await page.getByText('账号已启用',{exact:true}).waitFor();assert.equal(await scope.getByRole('button',{name:'编辑',exact:true}).getAttribute('aria-pressed'),'true');await page.getByText('授权有未保存修改',{exact:true}).waitFor();await page.keyboard.press('Escape');await cancel(page);assert.equal(await scope.getByRole('button',{name:'编辑',exact:true}).getAttribute('aria-pressed'),'true');});
 await scenario('feedback-old-list-failure-does-not-contaminate-compose','list-late',async({page,held,pending})=>{await feedback(page);await page.getByRole('button',{name:'新建反馈',exact:true}).click();await page.getByRole('button',{name:'返回列表',exact:true}).first().click();await held.promise;await page.getByRole('button',{name:'新建反馈',exact:true}).click();pending.release();await page.waitForTimeout(200);assert.equal(await page.getByText('W8 旧列表失败',{exact:true}).count(),0);});
 await scenario('feedback-real-conflict-preserves-admin-input','',async({page,send,get})=>{const row=await send('/api/feedback',{kind:'问题反馈',text:'W8 管理冲突'});await feedback(page);await page.getByRole('button').filter({hasText:'W8 管理冲突'}).click();await page.getByLabel('处理状态',{exact:true}).selectOption('已处理');await page.getByLabel('处理结果',{exact:false}).fill('W8 我的结果');await send('/api/feedback/'+row.id,{revision:row.revision,status:'处理中',result:''},'PATCH');await page.getByRole('button',{name:'保存处理',exact:true}).click();await page.getByText('该反馈已被其他管理员更新。你的输入已保留，请核对最新状态后再保存。',{exact:true}).waitFor();assert.equal(await page.getByLabel('处理结果',{exact:false}).inputValue(),'W8 我的结果');await page.getByRole('button',{name:'保存处理',exact:true}).click();await page.getByText('处理结果已保存。',{exact:true}).waitFor();assert.equal((await get('/api/feedback')).find(r=>r.id===row.id).result,'W8 我的结果');});
 await scenario('quotation-actual-app-busy-blocks-section-and-releases','quote-busy',async({page,held,pending,requests})=>{await enter(page,'产品报价管理');await page.getByRole('button',{name:'产品报价',exact:true}).click();await page.getByRole('button',{name:'K172-C',exact:true}).click();await page.getByRole('button',{name:'开始报价',exact:true}).click();await page.getByLabel('客户名称',{exact:true}).fill('W8 忙碌报价');await page.getByLabel('业务员',{exact:true}).fill('W8 合成');await page.getByRole('button',{name:'保存报价',exact:true}).click();await held.promise;await nav(page).getByRole('button',{name:'新聊天',exact:true}).evaluate(el=>el.click());assert.equal(await page.getByRole('alertdialog').count(),0);assert.equal(await page.getByLabel('客户名称',{exact:true}).inputValue(),'W8 忙碌报价');pending.release();await page.getByRole('alert').filter({hasText:'W8 合成忙碌写入失败'}).waitFor();assert.equal(requests.filter(r=>r.path==='/api/workbenches/sales/batches'&&r.method==='POST').length,1);});
 await scenario('procurement-actual-app-busy-blocks-section-and-keeps-input','procurement-busy',async({page,held,pending})=>{await enter(page,'原料价格管理');await page.getByRole('button',{name:'原料价格',exact:true}).click();await page.getByRole('button',{name:'编辑价格',exact:true}).click();await page.getByRole('textbox',{name:'搜索原料',exact:true}).fill('A');await page.getByRole('textbox',{name:'A待发布价',exact:true}).fill('31');await page.getByRole('button',{name:/^保存修改/}).click();const dialog=page.getByRole('dialog',{name:'保存价格修改'});await dialog.getByLabel('录价说明',{exact:true}).selectOption('供应商报价');await dialog.getByRole('button',{name:'确认并保存',exact:true}).click();await held.promise;await nav(page).getByRole('button',{name:'新聊天',exact:true}).evaluate(el=>el.click());assert.equal(await page.getByRole('alertdialog').count(),0);assert.equal(await page.getByRole('textbox',{name:'A待发布价',exact:true}).inputValue(),'31');pending.release();await page.getByText('W8 合成忙碌写入失败',{exact:false}).waitFor();});
 await scenario('research-actual-app-busy-blocks-section-and-keeps-input','research-busy',async({page,held,pending})=>{await enter(page,'产品成本计算');await page.getByRole('button',{name:'产品成本',exact:true}).click();await page.getByRole('button',{name:'K172-C',exact:true}).first().click();await page.getByRole('button',{name:'编辑配方',exact:true}).click();const reason=page.getByRole('alertdialog',{name:'记录调整原因'});await reason.getByRole('button',{name:'配方优化',exact:true}).click();await reason.getByRole('button',{name:'进入编辑',exact:true}).click();await page.getByRole('spinbutton',{name:'收率百分比'}).fill('95');await page.getByRole('button',{name:'试算双成本',exact:true}).click();await page.getByText('试算完成，可保存草稿',{exact:true}).waitFor();await page.getByRole('button',{name:'保存草稿',exact:true}).click();await held.promise;await nav(page).getByRole('button',{name:'新聊天',exact:true}).evaluate(el=>el.click());assert.equal(await page.getByRole('alertdialog').count(),0);assert.equal(await page.getByRole('spinbutton',{name:'收率百分比'}).inputValue(),'95');pending.release();await page.getByText('W8 合成忙碌写入失败',{exact:true}).waitFor();});
 await scenario('feedback-old-retry-error-does-not-contaminate-compose','retry-late',async({page,held,pending})=>{await feedback(page);await page.getByText('W8 首次列表失败',{exact:false}).waitFor();await page.getByRole('button',{name:'重试',exact:true}).click();await held.promise;await page.getByRole('button',{name:'新建反馈',exact:true}).click();pending.release();await page.waitForTimeout(200);assert.equal(await page.getByText('W8 旧重试失败',{exact:false}).count(),0);});
 await scenario('procurement-approved-home-exit-reopens-clean-editor','',async({page})=>{await enter(page,'原料价格管理');await page.getByRole('button',{name:'原料价格',exact:true}).click();await page.getByRole('button',{name:'编辑价格',exact:true}).click();await page.getByRole('textbox',{name:'搜索原料',exact:true}).fill('A');await page.getByRole('textbox',{name:'A待发布价',exact:true}).fill('31');await nav(page).getByRole('button',{name:'返回主页',exact:true}).click();await page.getByRole('alertdialog').getByRole('button',{name:'放弃修改',exact:true}).click();await page.getByRole('button',{name:'进入工作台',exact:true}).click();await page.getByRole('button',{name:'原料价格',exact:true}).click();await page.getByRole('button',{name:'编辑价格',exact:true}).waitFor();assert.equal(await page.getByRole('textbox',{name:'A待发布价',exact:true}).count(),0);});
 await scenario('research-approved-home-exit-removes-old-drawer','',async({page})=>{await enter(page,'产品成本计算');await page.getByRole('button',{name:'产品成本',exact:true}).click();await page.getByRole('button',{name:'K172-C',exact:true}).first().click();await page.getByRole('button',{name:'编辑配方',exact:true}).click();const reason=page.getByRole('alertdialog',{name:'记录调整原因'});await reason.getByRole('button',{name:'配方优化',exact:true}).click();await reason.getByRole('button',{name:'进入编辑',exact:true}).click();await page.getByRole('spinbutton',{name:'收率百分比'}).fill('95');await nav(page).getByRole('button',{name:'返回主页',exact:true}).evaluate(el=>el.click());await page.getByRole('alertdialog').getByRole('button',{name:'放弃修改',exact:true}).click();await page.getByRole('button',{name:'进入工作台',exact:true}).waitFor();assert.equal(await page.getByRole('spinbutton',{name:'收率百分比'}).count(),0);await page.getByRole('button',{name:'进入工作台',exact:true}).click();assert.equal(await page.getByRole('dialog',{name:'编辑配方 · K172-C',exact:true}).count(),0);});
 await scenario('same-identity-revocation-hides-cached-module-on-status-failure','background-benches',async({page,initial,requests})=>{await enter(page,'原料价格管理');await page.getByRole('button',{name:'原料价格',exact:true}).click();await page.getByRole('button',{name:'编辑价格',exact:true}).click();await page.getByRole('textbox',{name:'搜索原料',exact:true}).fill('A');await page.getByRole('textbox',{name:'A待发布价',exact:true}).fill('31');await page.evaluate(user=>window.w8User({...user,is_system_admin:false,scope_levels:{research:2}}),initial);await page.getByRole('button',{name:'进入工作台',exact:true}).waitFor();assert.equal(await page.getByRole('textbox',{name:'A待发布价',exact:true}).count(),0);assert.equal(await page.getByRole('button').filter({hasText:'原料价格管理'}).filter({has:page.locator('em')}).count(),0);assert.equal(await page.getByRole('button',{name:'采购看板',exact:true}).count(),0);assert.equal(requests.filter(r=>r.method!=='GET').length,0);});
 await scenario('procurement-import-draft-local-shared-and-refresh-protection','',async({page})=>{await enter(page,'原料价格管理');await page.getByRole('button',{name:'原料价格',exact:true}).click();await page.getByRole('button',{name:'导入报表',exact:true}).click();const input=page.getByLabel('来源名称',{exact:true});await input.fill('W8 来源草稿');await page.getByRole('button',{name:'关闭导入',exact:true}).click();await cancel(page);assert.equal(await input.inputValue(),'W8 来源草稿');await nav(page).getByRole('button',{name:'新聊天',exact:true}).evaluate(el=>el.click());await cancel(page);assert.equal(await input.inputValue(),'W8 来源草稿');await Promise.all([page.waitForEvent('dialog').then(dialog=>{assert.equal(dialog.type(),'beforeunload');return dialog.dismiss()}),page.evaluate(()=>location.reload())]);assert.equal(await input.inputValue(),'W8 来源草稿');});
 await scenario('procurement-import-busy-blocks-app-exit','import-busy',async({page,held,pending})=>{await enter(page,'原料价格管理');await page.getByRole('button',{name:'原料价格',exact:true}).click();await page.getByRole('button',{name:'导入报表',exact:true}).click();const input=page.getByRole('dialog',{name:'导入价格',exact:true}).locator('textarea');await input.fill('编号,名称,单位,最新价\nA,原料A,kg,31\n');await page.getByRole('button',{name:'检查数据',exact:true}).click();await held.promise;assert.equal(await input.isDisabled(),true);const frozenInput=await input.inputValue();await input.click({force:true});await page.keyboard.press('2');assert.equal(await input.inputValue(),frozenInput);await nav(page).getByRole('button',{name:'新聊天',exact:true}).evaluate(el=>el.click());assert.equal(await page.getByRole('alertdialog').count(),0);assert.ok((await input.inputValue()).includes('原料A'));pending.release();await page.getByText('W8 合成导入检查失败',{exact:false}).waitFor();});
 await scenario('procurement-publish-draft-busy-and-refresh-protection','publish-busy',async({page,held,pending,requests})=>{await enter(page,'原料价格管理');await page.getByRole('button',{name:'原料价格',exact:true}).click();await page.getByRole('button',{name:'启用价格',exact:true}).click();await page.getByRole('button',{name:/^定时启用/}).click();await nav(page).getByRole('button',{name:'新聊天',exact:true}).evaluate(el=>el.click());await cancel(page);assert.equal(await page.getByRole('button',{name:/^定时启用/}).getAttribute('aria-pressed'),'true');await page.getByRole('button',{name:/^立即启用/}).click();await page.getByRole('button',{name:'确认启用',exact:true}).click();await held.promise;await nav(page).getByRole('button',{name:'新聊天',exact:true}).evaluate(el=>el.click());assert.equal(await page.getByRole('alertdialog').count(),0);await Promise.all([page.waitForEvent('dialog').then(dialog=>{assert.equal(dialog.type(),'beforeunload');return dialog.dismiss()}),page.evaluate(()=>location.reload())]);pending.release();await page.getByText('W8 合成启用失败',{exact:false}).waitFor();assert.equal(requests.filter(r=>r.path.endsWith('/publish')&&r.method==='POST').length,1);});
 await scenario('procurement-confirm-import-busy-blocks-app-exit','import-write-busy',async({page,held,pending,get,requests})=>{await enter(page,'原料价格管理');await page.getByRole('button',{name:'原料价格',exact:true}).click();await page.getByRole('button',{name:'导入报表',exact:true}).click();const input=page.getByRole('dialog',{name:'导入价格',exact:true}).locator('textarea');await input.fill('编号,名称,单位,最新价\nA,原料A,kg,31\n');await page.getByRole('button',{name:'检查数据',exact:true}).click();await page.getByLabel('录价说明',{exact:true}).selectOption({label:'供应商报价'});await page.getByRole('button',{name:'确认并导入',exact:true}).click();await held.promise;assert.equal(await input.isDisabled(),true);await nav(page).getByRole('button',{name:'新聊天',exact:true}).evaluate(el=>el.click());assert.equal(await page.getByRole('alertdialog').count(),0);assert.ok((await input.inputValue()).includes(',31'));pending.release();await page.getByText('W8 合成导入写回失败',{exact:false}).waitFor();assert.equal((await get('/api/workbenches/procurement/overview')).current_update,null);assert.equal(requests.filter(r=>r.path==='/api/workbenches/procurement/imports'&&r.method==='POST').length,1);});
 if(red)throw new Error('Original reproduction unexpectedly passed');
 writeFileSync('.scratch/w8-20261003/browser-results.json',JSON.stringify(evidence,null,2));process.stdout.write(JSON.stringify(evidence));
}finally{await browser?.close();await server.close();}
